### ISSUE TITLE
Manually run Data Pipeline fails

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#105]
This issue was originally in https://github.com/onnela-lab/Beiwe-Analysis/issues/5, but I think that is more related to this repo.

-----------------------------------

When I try to run the Data Pipeline manually from a study, I get this issue:

> Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed

I'll try to see why this happened and keep this post updated.

Edit: I went to the logs of ElasticBeanstalk and got this:

> ERROR in app: Exception on /run-manual-code/2 [POST]
> Traceback (most recent call last):
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 107, in get_current_region
>      return full_region.split(" ")[1][:-1]
> TypeError: a bytes-like object is required, not 'str'
>  
> During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 111, in get_current_region
>      return check_output(["ec2metadata", "--availability-zone"]).strip()[:-1]
>    File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
>      **kwargs).stdout
>    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
>      with Popen(*popenargs, **kwargs) as process:
>    File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
>      restore_signals, start_new_session)
>    File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
>      raise child_exception_type(errno_num, err_msg, err_filename)
>  FileNotFoundError: [Errno 2] No such file or directory: 'ec2metadata': 'ec2metadata'
>  
> During handling of the above exception, another exception occurred:
>  
> Traceback (most recent call last):
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
>      response = self.full_dispatch_request()
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
>      rv = self.handle_user_exception(e)
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
>      reraise(exc_type, exc_value, tb)
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>      raise value
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
>      rv = self.dispatch_request()
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
>      return self.view_functions[rule.endpoint](**req.view_args)
>    File "/opt/python/current/app/libs/admin_authentication.py", line 174, in authenticate_and_call
>      return some_function(*args, **kwargs)
>    File "/opt/python/current/app/api/data_pipeline_api.py", line 20, in run_manual_code
>      pipeline_region = get_current_region()
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 113, in get_current_region
>      raise Exception("get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed")
> Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed
>  
> Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
> ['Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed', '  File "flask/app.py", line 2446, in wsgi_app', '  File "flask/app.py", line 1951, in full_dispatch_request', '  File "flask/app.py", line 1820, in handle_user_exception', '  File "flask/_compat.py", line 39, in reraise', '  File "flask/app.py", line 1949, in full_dispatch_request', '  File "flask/app.py", line 1935, in dispatch_request', '  File "libs/admin_authentication.py", line 174, in authenticate_and_call', '  File "api/data_pipeline_api.py", line 20, in run_manual_code', '  File "pipeline/configuration_getters.py", line 113, in get_current_region']

As a summary:

1. Code related error:
    - File: "/opt/python/current/app/pipeline/configuration_getters.py",
    - Line: 107
    - Method: in get_current_region
    - Statement: `return full_region.split(" ")[1][:-1]`
    - Error: `TypeError: a bytes-like object is required, not 'str'`
2. Missing `ec2metadata`: `get_current_region` can only be called on an amazon server with `ec2metadata/ec2-metadata` installed.

For this error, could we make so instead of requiring the EC2 to have `ec2metadata` installed, we could just get the information form a `curl` to `http://169.254.169.254`?

If we run `curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document` we will get the detail of the EC2 running the command. For example, in my case, I can get this info from running that command on the environment machine:

> {
>   "accountId" : <hidden by me>,
>   "architecture" : "x86_64",
>   "availabilityZone" : "eu-west-1b",
>   "billingProducts" : null,
>   "devpayProductCodes" : null,
>   "marketplaceProductCodes" : null,
>   "imageId" : <hidden by me>,
>   "instanceId" : <hidden by me>,
>   "instanceType" : "t2.medium",
>   "kernelId" : null,
>   "pendingTime" : <hidden by me>,
>   "privateIp" : <hidden by me>,
>   "ramdiskId" : null,
>   "region" : "eu-west-1",
>   "version" : <hidden by me>
> }

As you see, we could process this JSON and get the `region id` without imposing the requirement to install the `ec2metadata` package. What do you think?

3. I should set up my Sentry server...

**Comment by usanchez** [comment]
Okay, so I plugged in my suggested change for error 2 and got rid of error 1 too. This is the piece of code that I've plugged in `get_current_region`:

```python3
def get_current_region():
    ec2_instance_identity_url = "http://169.254.169.254/latest/dynamic/instance-identity/document"
    ec2_instance_identity_response = requests.get(ec2_instance_identity_url)
    ec2_instance_region = ec2_instance_identity_response.json()["region"]

    return ec2_instance_region
```

No checks or anything, it was a fast testing.

However, solving this, led me to the following new error:

>["FieldError: Invalid field name(s) for model StudyRelation: 'is_batch_user'.", '  File "api/data_pipeline_api.py", line 30, in run_manual_code', '  File "pipeline/index.py", line 37, in refresh_data_access_credentials', '  File "django/db/models/manager.py", line 85, in manager_method', '  File "django/db/models/query.py", line 459, in get_or_create', '  File "django/db/models/query.py", line 537, in _extract_model_params']
>OCCURRED 1 TIMES:
>FieldError("Invalid field name(s) for model StudyRelation: 'is_batch_user'.",)
>  File "/opt/python/current/app/api/data_pipeline_api.py", line 30, in run_manual_code
>    refresh_data_access_credentials('manually', ssm_client=ssm_client, webserver=True)
>  File "/opt/python/current/app/pipeline/index.py", line 37, in refresh_data_access_credentials
>    is_batch_user=True,
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
>    return getattr(self.get_queryset(), name)(*args, **kwargs)
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 459, in get_or_create
>    lookup, params = self._extract_model_params(defaults, **kwargs)
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 537, in _extract_model_params
>    "', '".join(sorted(invalid_params)),

The error is quite clear that the field `is_batch_user` is invalid for the model `StudyRelation`. If I go to `user_model.py`, I see that, indeed, that field does not exist in `StudyRelation`:

```python3
class StudyRelation(AbstractModel):
    """
    This is the through-model for defining the relationship between a researcher and a study.
    There are these relatioships:
        site admin
        study admin
        researcher
    """
    study = models.ForeignKey(
        'Study', on_delete=models.PROTECT, related_name='study_relations', null=False, db_index=True
    )
    researcher = models.ForeignKey(
        'Researcher', on_delete=models.PROTECT, related_name='study_relations', null=False, db_index=True
    )
    relationship = models.CharField(max_length=32, null=False, blank=False, db_index=True)

    class Meta:
        unique_together = ["study", "researcher"]

    def __str__(self):
        return "%s is a %s in %s" % (self.researcher.username,
                                     self.relationship.replace("_", " ").title(),
                                     self.study.name)
```

However, the field `is_batch_user` is referenced many times in the code and is located in `Researcher`:

```python3
class Researcher(AbstractPasswordUser):
    """
    The Researcher database object contains the password hashes and unique usernames of any
    researchers, as well as their data access credentials. A Researcher can be attached to
    multiple Studies, and a Researcher may also be an admin who has extra permissions.
    A Researcher uses web, so their passwords are hashed accordingly.
    """

    username = models.CharField(max_length=32, unique=True, help_text='User-chosen username, stored in plain text')
    site_admin = models.BooleanField(default=False, help_text='Whether the researcher is also an admin')

    access_key_id = models.CharField(max_length=64, validators=[standard_base_64_validator], unique=True, null=True, blank=True)
    access_key_secret = models.CharField(max_length=44, validators=[url_safe_base_64_validator], blank=True)
    access_key_secret_salt = models.CharField(max_length=24, validators=[url_safe_base_64_validator], blank=True)

    is_batch_user = models.BooleanField(default=False)
```

So, I think that we should remove the `is_batch_user` from the following piece of code that is located in the function `refresh_data_access_credentials` from `pipeline/index.py`, because that field does not exist in `StudyRelation`: 

```python3
StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            is_batch_user=True, # <-- This
        )
```

Additionally, in `admin_api.py`, function `add_researcher_to_study`, we also use the `StudyRelation.objects.get_or_create` function, but we don't filter by `is_batch_user`.

Also I found out that the parameters passed to the method are different:

- function `refresh_data_access_credentials` from `pipeline/index.py`, parameters: `study`, `researcher` and `relationship`.
- function `add_researcher_to_study` from `api/admin_api.py`, parameters: `study_id`, `researcher_id`, `relationship`

I guess that this does not matter because in one instance we are filtering by researcher object and in the second one we filter by researcher id. 

I see that the intention is to get (or create) those study relationships that contain Batch users, but as this problematic field is not in `StudyRelation`, maybe we could add this filter to the mock_researcher some lines above? What I mean is, instead of having this:

```python3
    researcher_name = 'BATCH USER {}'.format(freq)
    mock_researchers = Researcher.objects.filter(username=researcher_name)
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
    else:
        mock_researcher = mock_researchers.get()
        mock_researcher.save()

    # Ensure that the Researcher is attached to all Studies. This allows them to access all
    # data via the DAA.
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            is_batch_user=True,
        )
```

We could have this:

```python3
    researcher_name = 'BATCH USER {}'.format(freq)
    mock_researchers = Researcher.objects.filter(username=researcher_name, is_batch_user=True)
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
    else:
        mock_researcher = mock_researchers.get()
        mock_researcher.save()

    # Ensure that the Researcher is attached to all Studies. This allows them to access all
    # data via the DAA.
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher
        )
```

And this would solve the issue (I think). What do you think? 

Maybe I've made a mistake elsewhere and this wall of text has no sense xD

**Edit**: I tested my proposed piece of code and got that the researcher/user _BATCH USER manually_ is not a batch user:

First, I tried to see whether I could get the `mock_researchers`:

```python3
In [1]: freq = "manually"     
In [2]: researcher_name = 'BATCH USER {}'.format(freq)         
In [3]: mock_researchers = Researcher.objects.filter(username=researcher_name)                                              
In [4]: mock_researchers.get().username                                                                                     
Out[4]: 'BATCH USER manually'
```

There it is, now, trying the new way of filtering:

```python3
In [5]: mock_researchers = Researcher.objects.filter(username=researcher_name, is_batch_user=True)                         
In [6]: mock_researchers.get().username                                                                                    
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-11-60a2104c7648> in <module>
----> 1 mock_researchers.get().username

~/PycharmProjects/humanai-backend/venv/lib/python3.6/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    378             raise self.model.DoesNotExist(
    379                 "%s matching query does not exist." %
--> 380                 self.model._meta.object_name
    381             )
    382         raise self.model.MultipleObjectsReturned(

DoesNotExist: Researcher matching query does not exist.

In [7]: mock_researchers.get()                                                                                             
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-12-735bc98a09c6> in <module>
----> 1 mock_researchers.get()

~/PycharmProjects/humanai-backend/venv/lib/python3.6/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    378             raise self.model.DoesNotExist(
    379                 "%s matching query does not exist." %
--> 380                 self.model._meta.object_name
    381             )
    382         raise self.model.MultipleObjectsReturned(

DoesNotExist: Researcher matching query does not exist.
```

But it does not exist... So I tried to get the `is_batch_user` of this researcher:

```python3
In [8]: mock_researchers = Researcher.objects.filter(username=researcher_name)                                             
In [9]: mock_researchers.get().is_batch_user                                                                               
Out[9]: False
```

:surprised_pikachu_face:

I'll keep this post updated with the journey of discovering why this happened with the `is_batch_user` field...

**Edit2**: Okay, I think I got a reasonable explanation:

If the mock_researcher does not exist we create it with:
```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
```

If we go to the class method of Researcher:

```python3
    @classmethod
    def create_without_password(cls, username):
        """
        Create a new Researcher with provided username and no password
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                admin=False) # --> I think that this may be obsolete, because the Researcher model does not have this field, shouldn't it be site_admin?
        r.reset_access_credentials()
        return r
```

Besides, the `admin` field being obsolete (IMO), here, there is no way to tell the class to create a `Researcher` with `is_batch_user` set to `True` and by default, when a `Researcher` is created this field is set to false (`is_batch_user = models.BooleanField(default=False)`). Additionally, the _only_ use for the `create_without_password` classmethod is to create the `mock_researchers`.

So my suggestion is to change these previously mentioned lines:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
```

to:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_batch_user(username=researcher_name)
```

and additionally, changing the `create_without_password` classmethod to:

```python3
    @classmethod
    def create_batch_user(cls, username):
        """
        Create a new Researcher that serves as a Batch user
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                site_admin=False,
                is_batch_user=True)
        r.reset_access_credentials()
        return r
```

Or, if you want to maintain the previous version of the method:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(username=researcher_name, is_batch_user=True)
```

and:

```python3
    @classmethod
    def create_without_password(cls, username, is_batch_user=False):
        """
        Create a new Researcher with provided username and no password
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                site_admin=False,
                is_batch_user=is_batch_user)
        r.reset_access_credentials()
        return r
```

I'm so so sorry for this wall of text. Hope it helps anyway at least.

**Comment by biblicabeebli** [comment]
okay, I'm going to have to review pipeline deploy.

I also have interest from a third party in running their own custom code in the pipeline.  At this point I think pipeline needs to be pulled out into the cluster management and not this janky and weirdly apparently brittle set of direction.

**Comment by usanchez** [comment]
Hi,

Despite the changes in recent updates to the code, I've tested this bug and still happens. To solve it I've implemented the method `create_batch_user` stated before. Then, we got two options to avoid the error that occurs here:

```python3
for study in Study.objects.all():
    StudyRelation.objects.get_or_create(
        study=study,
        researcher=mock_researcher,
        relationship=ResearcherRole.researcher,
        is_batch_user=True,
    )
```

1. Remove the `is_batch_user` parameter because the `StudyRelation` model does not have it
2. Add a boolean field `is_batch_user` in the `StudyRelation` model.

Additionaly, we could make  a new `ResearcherRole` called `batch_user`, so we could use it here instead of `ResearcherRole.researcher`. I think it makes more sense than the current `is_batch_user` column in `Researcher`, because the `ResearcherRole` model already does the job of indicating which is the role of the `Researcher` object.

I went for the first option, because, this way, I don't have to make any migrations.

After deploying these changes I get no error in the EB, but the Pipeline fails, stating that it cannot find the runner.sh file:

```bash
/bin/bash: runner.sh: No such file or directory
```


Additionally, at the end of the `refresh_data_access_credentials` method we have this piece of code:

```python3
ssm_client.put_parameter(
    Name=access_key_ssm_name,
    Value=access_key,
    Type='SecureString',
    Overwrite=True,
)
ssm_client.put_parameter(
    Name=secret_key_ssm_name,
    Value=secret_key,
    Type='SecureString',
    Overwrite=True,
)
```

Is this duplicated code? or is it intentional?

**Comment by usanchez** [comment]
I was able to update the information manually by going to _Job definitions_ in _AWS Batch_, selecting the latest _Revision_ and clicking the _Create new revision_ button. Then in the modal that appears, go to the _Environment_ section and change the text inputs and text areas accordingly, e.g.:

- _Command_ (space delimited): `/bin/bash beiwe-analysis/Pipeline/utils/runner.sh`
- _vCPUs_: `2`
- _Memory (MiB)_: `15500`

This changes refer to the content that is in the `container-props.json` file, but I haven't checked yet what would be the way to update the rest of the configuration to match it to the rest of the JSON files.

The good thing about AWS is that, if I was able to do it with the console, there is a way to do it using the CLI or their API, so that code could be added to the `update_docker.py` script.

After these changes, the jobs were run correctly, so this issue can be closed. I'll let it open for some time just in case anyone wants to add some discussion to it.

Thank you very much!

**Comment by biblicabeebli** [comment]
regarding that duplication of the ssm_client.put_parameter it looks like it has been there forom the initial development on this (not by me).  I'm fairly certain the api call is idempotent...  If you want to remove it and let me know... go ahead?  This is weird.

**Comment by biblicabeebli** [comment]
>     This file is only run with new setups of containers; when updating an existing container we are told to run python humanai-backend/pipeline/update_docker.py, but this only runs the run method form the docker_script.py file, thus, we are not running the piece of code needed to give the information of the JSON files to the container.

this seems important, and it is reminding me of my last review of the code, where I was thinking about getting RID of the update code as it doesn't exactly add anything, and just added complexity, and required a more involved high-level understanding of things to debug.

I've said it less directly before, at this point I'm strongly in favor of moving pipeline setup to the cluster management code.  Reduces user issues, collects boto3 code into fewer spots, simplifies the serverside code.

**Comment by biblicabeebli** [comment]
```
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            is_batch_user=True,
        )
```
should be
```
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            researcher__is_batch_user=True,
        )
    ```

Making that change, commiting it. pretty sure we are not done with this bug.

**Comment by biblicabeebli** [comment]
Okay, I think this is a response to your question and proposal about how to query the researchers there:
Researcher name is unique, so we don't need to do extra filtering above.

That said, I'm now puzzling over whether this introduces a database constraint violation (the study_relation + researcher being unique).  I think that requires screwed up mock users, but also mock users wouldn't have been generated recently.  Also that code is pretty inefficient, we can do better.

Adding improvement flag, this code should be cleaned up.

**Comment by biblicabeebli** [comment]
derp:
```
ssm_client.put_parameter(
    Name=access_key_ssm_name,
    Value=access_key,
    Type='SecureString',
    Overwrite=True,
)
ssm_client.put_parameter(
    Name=secret_key_ssm_name,
    Value=secret_key,
    Type='SecureString',
    Overwrite=True,
)
```
they are different, access key and secret key.

**Comment by usanchez** [comment]
lol
I'm sorry about that. Too many letters together xD

**Comment by usanchez** [comment]
Wouldn't it be better to just assign these BATCH users to the study when the study is created? That way we don't have to iterate over all studies to check if these users are assigned or not. Just an idea. The only downside I can think of is that if I want to create a test study where I don't want to execute the pipeline, these users are useless. Otherwise, it seems better for me.

**Comment by biblicabeebli** [comment]
Pipeline operations can run at arbitrary times for arbitrary studies with an arbitrary amount of concurrency. The batch user's creds are used by all of them, so it needs access to all studies.

**Comment by biblicabeebli** [comment]
Pipeline is deprecated, will be replaced with Forest.  Closing.
