### ISSUE TITLE
implement push notifications to enhance survey notifications on iOS and Android

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#107]
This feature request comes from Onnela Lab, its purpose is to improve the consistency and reliability of survey notifications on both iOS and Android.

Due to changes over time on both iOS and Android survey notifications have become less and less reliable (particularly on Android 9).  These notifications have been historically generated purely within the app, but the time has come to improve them through each platform's respective push notification service.

**Comment by biblicabeebli** [comment]
(Work on this is in-progress.)

This will eventually require a redeploy of management/worker servers.

**Comment by usanchez** [comment]
I've seen that the android repo has a branch that works on the push notifications. However, I've seen that it is being developed with Firebase. Why have you selected Firebase? Wouldn't it be easier to use a AWS service that offers SDKs both for Android and iOS for the push notifications?

Just asking because I have no idea about push notifications, but I know that AWS offers services like https://aws.amazon.com/pinpoint/features/engagement-channels/push-notifications/, that can do the job for both SDKs.

Thank you very much!

**Comment by biblicabeebli** [comment]
Firebase is the de-facto push notification platform for Android.

**Comment by biblicabeebli** [comment]
Development on this is still in-progress, but substantially developed.  Details yet to be resolved include live testing, and inserting additional credential handling into the launch script.

**Comment by usanchez** [comment]
When this feature is included, will the previous notification system be removed? (notification by internal alarms). Thank you!

**Comment by biblicabeebli** [comment]
I have no intention of removing it at this time, but unfortunately Android makes power management refinements with every version update that keep reducing the utility/reliability of all timed app events.  This causes problems all over the place, those timers control surveys and data recording sessions.  The in-app timers could get some attention in the future, we don't want them totally broken, but by now we have to accept that there are no guarantees that any on-device solution will remain viable over time.

**Comment by biblicabeebli** [comment]
(And right now there is a policy that we can't put an update up on the app store without setting a higher "target" os/sdk version, which would break timers in new and exciting ways.)

**Comment by biblicabeebli** [comment]
This issue is too out of date, closing.
Update: this is almost done.
