### ISSUE TITLE
update documentation for python3

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#109]
The wiki has not had a run-through for for python3 details.
In general, anything mentioning python 2 is deprecated, any CLI thing needs to be checked if it states python or python3 depending on linux version.

(the confusing place right now is the pipeline, sorry, will try and get to that soon.)

**Comment by usanchez** [comment]
How can others help update the docs? Should we just open issues and write the text there?

**Comment by jakeczyz** [comment]
One spot (to save you time): 

https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#configure-your-application

Under Step 2

**Comment by biblicabeebli** [comment]
keep em coming, I'll try and get to them tomorrow.

**Comment by biblicabeebli** [comment]
I've updated the deployment instructions (need to review, not marking as closed yet)
and the Data batching and indexing details pages.

I'm merging the current state of development into master and production.

**Comment by biblicabeebli** [comment]
@usanchez 
@jakeczyz 
I have created a new issue and pinned it (#127) so contributors can ask for edit rights.  (I had to create a test account to work out how to do it.)

Python 3 updates to the documentation are generally finished, obviously let me know if I am wrong.
