### ISSUE TITLE
Running Beiwe Backend Locally

### ISSUE THREAD

**Issue by ravibanks54** [onnela-lab/beiwe-backend#112]
What's the best way to get the beiwe backend server running locally for testing purposes? I see in the comments that I have to set up a local sqlite3 server, but it would be awesome if there was a step-by-step guide on this.

**Comment by biblicabeebli** [comment]
You don't need to set up a sqlite _server_, you just need sqlite install (it is probably installed, its one of those super duper common libraries.)

I hear your plea, I'm currently squashing bugs.

Feel free to post here with items related to documentation that you think should be added.  At some point I have to make a judgement about what is too basic or just not our job to handle (like python virtual environments) but if you want write something up it will probably get added.

**Comment by ravibanks54** [comment]
Hey Eli, thanks for getting back to me - appreciate you taking time out of your busy day. 
I was able to figure it out on my own thankfully - ran into some issues with connecting with the database but fixed it through some trial and error.
