### ISSUE TITLE
dedupe_chunks_script.py missing

### ISSUE THREAD

**Issue by er42** [onnela-lab/beiwe-backend#115]
We encountered a problem recently where data appear to be uploaded to S3 but do not make it into the database (i.e., are not visible on the dashboard or available for download). I suspected that this might be related to the ChunkRegistry duplication issue described on [this](https://github.com/onnela-lab/beiwe-backend/wiki/Help!-I'm-Trying-to-Deploy-and-Something's-Going-Wrong!) new wiki page. So, I tried following the steps outlined on that page to correct it.

Unfortunately, the critical dedupe_chunks_script.py file appears to be missing, and I can't find it anywhere on the github repo either. Is this code available somewhere?

**Comment by biblicabeebli** [comment]
This work is still in progress on the development branch, the dedupe script
is ready for production.
(I'm just back from my time away, have to review development, tackle a
couple things, and, then I will merge it into master and probably
production.)

**Comment by biblicabeebli** [comment]
I think sure the state of the development branch code is now ready, I squashed the bug that deduping caused in data processing.  Documentation to be updated as long as nothing new comes up.

**Comment by er42** [comment]
Ok, thanks. I just redeployed using the dev branch; we'll see if that works better.

**Comment by biblicabeebli** [comment]
I've been squashing a couple issues (nothing was broken, but there was some spam on the data processing server) in the time since you posted.  I need to go through documentation, then the code will be on master, probably production too.

**Comment by biblicabeebli** [comment]
This got lost in the churn, apologies.
If there are any documentation issues leave a comment on #127 and I'll give you wiki edit permissions

(Documentation should be generally much more up to date.  Pipeline is in flux.)
