### ISSUE TITLE
Feature Request: analysis / processing status page with way to view data cleaning and data analysis code processing status

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#121]
I haven't deployed the analysis pipeline yet, but one thing that appears missing from the documentation and code I've seen is an easy way for study admins to view the status and logs of cron jobs that had run.  This would be very useful for managing and monitoring a deployed pipeline.

**Comment by biblicabeebli** [comment]
Such a feature would probably be helpful for the regular data processing too.

This is a good idea, right now there is other ongoing work on pipeline that is going to block this.  I'm writing a proposal/issue for rethinking the pipeline "spec," it is currently a pain-point within Beiwe.  There are some technical details and limitations, mostly with querying AWS APIs for statuses etc.  

In principle I don't want to lock developers/researchers into only using AWS Batch, but that is what the pipeline uses.  I also don't want to __require__ developers to manually to call back to the Beiwe Server.  My initial thought is to have a cluster management script deploy a bash/python script that does a couple things.  Execute a file in a call from the beiwe server, redirect I/O to a single output file, and then uploading it to the Beiwe server at the end of work even if it errors, and have the Beiwe server check on the job's ending status - some conditions, I'm thinking out of memory errors, will need that api check.

Also we should track active jobs and how long they have been running, and maintain a history of jobs completed.

**Comment by biblicabeebli** [comment]
renaming due to "pipeline" being erroneous due to project architecture changes.

**Comment by biblicabeebli** [comment]
This is on the forest analysis pages, closing this issue and creating a new one about improving the data available.
