### ISSUE TITLE
Internal server error after updating EBL platform

### ISSUE THREAD

**Issue by benazir46** [onnela-lab/beiwe-backend#125]
As suggested by Amazon we updated the EBL platform to Amazon Linux/2.9.5 from 2.8.6. Unfortunately, the website is down after that. I'm getting this error messages repeatedly on the EBL log:

> [Wed Feb 12 02:06:20.516840 2020] [:error] [pid 4565] [remote 172.31.11.180:24] ImportError: No module named contrib.fixers
[Wed Feb 12 02:06:20.637698 2020] [:error] [pid 4564] [remote 172.31.11.180:16152] mod_wsgi (pid=4564): Target WSGI script '/opt/python/current/app/wsgi.py' cannot be loaded as Python module.
[Wed Feb 12 02:06:20.637721 2020] [:error] [pid 4564] [remote 172.31.11.180:16152] mod_wsgi (pid=4564): Exception occurred processing WSGI script '/opt/python/current/app/wsgi.py'.
[Wed Feb 12 02:06:20.637739 2020] [:error] [pid 4564] [remote 172.31.11.180:16152] Traceback (most recent call last):
[Wed Feb 12 02:06:20.637759 2020] [:error] [pid 4564] [remote 172.31.11.180:16152]   File "/opt/python/current/app/wsgi.py", line 7, in <module>
[Wed Feb 12 02:06:20.637787 2020] [:error] [pid 4564] [remote 172.31.11.180:16152]     from app import app as application
[Wed Feb 12 02:06:20.637795 2020] [:error] [pid 4564] [remote 172.31.11.180:16152]   File "/opt/python/current/app/app.py", line 6, in <module>
[Wed Feb 12 02:06:20.637807 2020] [:error] [pid 4564] [remote 172.31.11.180:16152]     from werkzeug.contrib.fixers import ProxyFix
[Wed Feb 12 02:06:20.637822 2020] [:error] [pid 4564] [remote 172.31.11.180:16152] ImportError: No module named contrib.fixers

I tried installing the Requirements.txt from "/opt/python/current/app/ folder and restarting the server. We haven’t updated to python 3.6 yet. We deployed a fresh version from the master branch on 2 August, 2019.

**Comment by biblicabeebli** [comment]
This is a python layer dependency.  I'm not sure what version (branch) of the software you are deploying here.

Try checking out onto the `python2-legacy` branch and running a deploy command.

If that doesn't work, try the `downtime` branch, and then go back to the legacy branch.

(Elastic Beanstalk version shouldn't be... relevant? doing this, sounds like the deploy operation is screwed up.  You may need to deploy)

Definitely recommend upgrading to Python 3, by following the directions in the wiki.

**Comment by benazir46** [comment]
I tried to deploy from both the branches, but it throws the following error:

> Creating application version archive "app-19298-200217_151401".
Uploading Beiwe Cluster/app-19298-200217_151401.zip to S3. This may take a while.
Upload Complete.
> ERROR: InvalidParameterValueError - No Environment found for EnvironmentName = 'beiwe'

We deployed from the master branch that had the last commit on 24 Jul 2019 "an out of memory and disk space ever, upping those con…".  If I run eb deploy from that commit, it finds the environment name and deploys it successfully, but the site still remains down. The ELB is periodically terminating and creating a new EC2 instance.

After that we received an email from Amazon stating, "We detected an issue with your Auto Scaling group arn:aws:autoscaling:ap-southeast-2:XXXXXXX:autoScalingGroup:52180637-f51c-4a47-999e-fe1d77af5595:autoScalingGroupName/data-pipeline-env-asg-754c966c-d974-3c8e-95a4-5981ff96f855 in AWS account XXXXXXX. A security group associated with this Auto Scaling group cannot be found. Each time a scale out operation is performed, it will be prevented until you make a change that fixes the issue.".

The security group associated with the load balancer has a description: "Elastic Beanstalk created security group used when no ELB security groups are specified during ELB creation". I don't whether it is suppose to be that.

What should we do? If we need to re-deploy the whole setup (we hope not), will we still be able to download the saved data on S3 from the new web interface?

**Comment by benazir46** [comment]
Closing this as we have shutdown the entire server.

**Comment by biblicabeebli** [comment]
> Creating application version archive "app-19298-200217_151401".
Uploading Beiwe Cluster/app-19298-200217_151401.zip to S3. This may take a while.
Upload Complete.
ERROR: InvalidParameterValueError - No Environment found for EnvironmentName = 'beiwe'

I'm fairly confident this means there was a typo in your aws command line operation, providing beiwe as the platform name?

Let me know if you still have your rds database and need help restoring data.

**Comment by benazir46** [comment]
Nah, I edited the log before publishing here.

The data was saved, so we deleted everything. Thank you for your help.

**Comment by biblicabeebli** [comment]
Do you have a database backup?  The database contains the decryption keys.

**Comment by benazir46** [comment]
Sorry, didn't notice this earlier. We downloaded all the unencrypted data after the trial had ended. So our client decided to shutdown the server anyway. We don't need those data anymore.
