### ISSUE TITLE
Django 1.11 getting no support after April 2020

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#129]
Looking at this table: https://www.djangoproject.com/download/#supported-versions
I see that Django 1.11 will be deprecated in April 2020. I also see that it is the only version to support Python2.7. As we are already in Python3, I think that it will be a good idea to move to a higher version. Some viable options could be:

- Moving to the closest LTS: The closest and only LTS version is 2.2, with support until April 2022.
- Upgrading to the highest version: 3.0 would be the highest version right now, but a higher version is published every year, and, for non-LTS versions, its support lasts one year.
- Going fo the next LTS version: this would require us to upgrade to 3.0, then to 3.1 when 3.0 gets deprecated, and when 3.1 gets deprecated, we could move to a 3.2 LTS version, which would have support until 2024.

I didn't see any incompatibilities with other libraries, but maybe there is something that I didn't check.

What do you think?

**Comment by biblicabeebli** [comment]
Thanks for the heads up.

I will want to upgrade to the most recent lts.  We only use the database component of django, so the normal swath of a migration won't be as involved.  Mostly the thing to be careful about is the database field declaration changes.

(django 1.11 was the last version with python 2 support.)

**Comment by biblicabeebli** [comment]
I have committed changes for the Django 2.2 update.  Due to the other database changes currently present in the current feature development (push notifications) it will be rolled into that.

**Comment by biblicabeebli** [comment]
closing this issue as it has been completed, it will be making its way into development soon, then master, and production once testing on our staging server is complete.
