### ISSUE TITLE
Advice for troubleshooting ProcessingOverlapError

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#134]
Our (scalable, using Elastic Beanstalk) backend deployment had been unused after initial deployment for two months due to project delays, and I just checked into sentry to find that it's been raising ProcessingOverlapErrors for quite some time.  E.g.

`DATA PROCESSING OVERLOADED, CHECK SERVER.
Data processing has overlapped with a prior data index run that started more than 15.0 minutes ago.  That prior run has been going for 656 hour(s), 30 minute(s)`

I performed a git pull and eb deploy after discovering this error on Sunday night, but it’s persisted.

What is a recommended approach to troubleshoot this error?  Clearly, some process or file lock is stuck, but I'm working on this project using borrowed time and thought I'd ask if there were known causes before delving deeply into the code myself. :) Any tips or advice would be much appreciated!

**Comment by biblicabeebli** [comment]
Hi Jake.

Right now I recommend terminating and redeploying your data processing (workers and the manager) server(s).  This is an older error message, I rearchitected

**Comment by biblicabeebli** [comment]
(make sure to pull and run deployment off of either the master or production branch using the launch script.)

**Comment by biblicabeebli** [comment]
can I get a comment on this? would like to close.

**Comment by jakeczyz** [comment]
Thanks Eli! Sorry; I've been away from this project some days.  

By "terminating and redeploying your data processing" do you mean executing an ElasticBeanstalk "Rebuild Environment"?  If so, it looks like I'll need to create a snapshot of the RDS DB and restore from it after recreation.   Or, did you have another approach in mind?

**Comment by biblicabeebli** [comment]
I'm referring to the data processing servers, aka a manger and optional worker(s) server, these are the servers that you deploy using the cluser management script's deploy manager and worker commands.  They are not EB servers, they run ubuntu.  Were you running without them?  They are a necessary component of a beiwe cluster...

**Comment by jakeczyz** [comment]
Ah, sorry, yes, the servers created via` cluster_manager/launch_script.py.`   I didn't see an option/code path in that script for termination, so, manually via EC2 I terminated the two running machines (had a manager and one worker running before), and then I re-ran `python launch_script.py -create-manager` to re-create the manager machine.  As I'm no longer seeing the error, I presume this resolved the problem, but will post again if something is still amiss.  Thanks for your help!
