### ISSUE TITLE
At registration, check that phone receives key and device settings, not just 200 OK

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#138]
Currently, during registration, the Android app only checks to see if it gets an HTTP 200 OK response from the server.  But if the participant entered the wrong server URL and the phone is sending the registration request to some random website instead of to a Beiwe deployment, that random website might send back a 200 OK and make the app _think_ it's registered properly, when in fact it hasn't.

We've seen this happen on the Android app a few times (for example, [here](https://sentry.io/organizations/onnela-lab/issues/1635227627/)), where RegisterActivity sent its POST request to the server and instead of getting back JSON, it got back some random HTML, which probably indicates that it hit a website that's not a Beiwe deployment.  Shortly thereafter, the same Android app crashes because it tried to encrypt a file but doesn't have an encryption key; the error is `FileNotFoundException ... /org.beiwe.app/files/keyFile (No such file or directory)` (example [here](https://sentry.io/organizations/onnela-lab/issues/1635255283/)).

The fix is to **make sure the app only completes registration if it gets everything it needs from the server, including the key file and the study device settings JSON**.  We should make sure this is the case in **both the Android and the iOS apps**.

**Comment by biblicabeebli** [comment]
This has been implemented on Android.
@tjaeni01 I'm going to assign this issue to you, we should discuss whether we will try to incorporate this into the current state of the app.

**Comment by biblicabeebli** [comment]
@tjaeni01 
did weget this implemented on the ios app?

**Comment by tjaeni01** [comment]
Yes, this has been implemented in the push notifications update for the iOS app
