### ISSUE TITLE
Cluster ceased collecting data

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#165]
My study researchers are reporting that there is no recent data being collected.  The environment shows OK in EB and Sentry reports no errors.  I didn't see anything obvious in /var/log on the instance.   What's a way I can investigate if data is actually being collected from participants?    Relatedly, I tried to get into the RDS Postgres DB, using the db credentials in the environment on the node (discovered via `env | grep RDS_`), but the password is failing.   Any tips on this detail as well?

**Comment by jakeczyz** [comment]
Upon further investigation, it looks like there is no data since August 8th, which coincides with the cluster outage that was caused by the non-pegged dependencies [1] (and automatic EB restart setting to attempt to alleviate disk filling up [2]).  

The cluster appeared to be fine after that August fix, with the UI working as expected, including participant enrollments.  However, silently, it appears the system had stopped collecting data.  New participants had been enrolled weekly since then, but no recent data after August 8th shows up for any measurement (e.g. Power State) in the study dashboard.   Any advice on how to investigate and remedy this?   The effect of this issue on the study has been adverse, to say the least. :( 

[1] https://github.com/onnela-lab/beiwe-backend/issues/150
[2] https://github.com/onnela-lab/beiwe-backend/issues/143

**Comment by biblicabeebli** [comment]
Sounds like your processing server got a little screwy. Terminate your data processing and manager servers and deploy new ones.

**Comment by jakeczyz** [comment]
Thanks. What's the exact recommended way to do this safely?

**Comment by biblicabeebli** [comment]
Log in to the online aws console and terminate the manager and any workers, the run the deploy manager command in the launch script.  New processing servers will clone the codebase from the the repo, so you need to make sure that the version of the codebase running locally, on EB servers, and on processing servers are all up to date with the master branch.

**Comment by jakeczyz** [comment]
Thanks. Did it, and am now seeing data from the previously dark period.   

One feature suggestion I would make is to improve visibility/monitoring of the system components, so that problems like this can be alerted on via sentry (or aws notifications).   (It might also be useful to add this scenario and fix to a new troubleshooting section of the wiki. ) 

Thanks for your help, Eli.

**Comment by biblicabeebli** [comment]
Oh it is on my wishlist too.

**Comment by ruzicll** [comment]
> Log in to the online aws console and terminate the manager and any workers, the run the deploy manager command in the launch script. New processing servers will clone the codebase from the the repo, so you need to make sure that the version of the codebase running locally, on EB servers, and on processing servers are all up to date with the master branch.

Hi @biblicabeebli, I tried this as the fix to repeated CeleryNotRunningException (as per [158](https://github.com/onnela-lab/beiwe-backend/issues/158)), but after running `eb deploy` there's still no data processing server instance. Is there a way to get a data processing manager running again?

(Side note: I believe I have successfully done this other times with `reboot instance` in the AWS console.)

**Comment by biblicabeebli** [comment]
hello!

I believe your issue is very simple, I think you have confused the `eb deploy` command line command with the operation of deploying a new data processing server.

Run the launch script dot py in cluster_management, it will display the available commands if you provide it no arguments.  There are two commands: terminate workers and managers, and deploy manager.  Run the terminate command, then run the deploy manager command.

This will manually launch and configure a data processing server based on the contents of your settings files.  You need one manager (managers have the extra duty of distributing tasks), and you can add extra workers if you need them.

(I don't think I've seen you on here, I'm trying to get a little more active again, would be great if you could drop me an email at biblicabeiwe at gmail dot com, trying to stay current on our userbase.
