### ISSUE TITLE
Deploy of cluster server seems to be successful, page is still loading

### ISSUE THREAD

**Issue by mikej561** [onnela-lab/beiwe-backend#166]
Dear community, me with @matalukes have tried several times to deploy our cluster server (always successfully), however we cannot load the page (both our domain and load balancer's url). We have followed every step of this guide (https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment). We have just skipped creating an Sentry.IO account as we do not need it, otherwise everything should be fine. Has anybody encountered a similar problem? Is there something missing in the guide or something more we need to do? Thank you for your help.

**Comment by biblicabeebli** [comment]
Did you add the load balancer forwarding rule, port 443 to 80, after setting up the ssl certificate?

**Comment by biblicabeebli** [comment]
Can you let me know if that was your issue?

**Comment by matalukes** [comment]
Hi @biblicabeebli , thank you for your tip. We didn't have this rule, but after we added it, the problem remained the same.
![balancer_forwarding](https://user-images.githubusercontent.com/52035924/95438571-c4e34c00-0956-11eb-9566-47e7b9fba3cc.png)

**Comment by biblicabeebli** [comment]
Okay, not sure exactly what is going on there.

Try doing a new `eb deploy` operation, and check the security group (firewall rules) to make sure the load balancer is accepting connections on ports 80 and 443.

If that doesn't work can you contact me out-of-band by email?  eli@zagaran.com
I'll try and help you out, might need some debugging.  Sorry about the deployment issues.

**Comment by biblicabeebli** [comment]
relevant content from some out-of-band communication:

The underlying issue is that your server appears to be _unresponsive_, not broken in a code sense.  I know that because of your description that the browser spins and eventually gives up.

When you spin up an elastic beanstalk environment there is a default apache server configuration that will respond with a generic error message when a request comes in.  The Beiwe server has similar behavior, 404s for bad endpoints and 500s if something has gone horribly wrong.  Point is, you aren't even hitting these.

The following causes are possible:
1) The step you have already taken with the load balancer certificate for port 443. (It requires that a certificate be present, and that requires manual human work be done [or at least it did as of the last development of this feature], so we can't automate it.)
2) That the security groups (AWS special terminology for a firewall rule) allow traffic on the correct port between the load balancer and the elastic beanstalk server, and that the internet-facing load balancer accept connections on ports 80 and 443.
3) There was a screwup with the URL configuration / with the DNS setup.

**Comment by matalukes** [comment]
I think that I have managed to solve the problem with security groups, but now I got 500 Internal Server Error. Any ideas how to solve it?
![image](https://user-images.githubusercontent.com/52035924/97853842-f69ec700-1cf8-11eb-8595-de5effdb16df.png)
The corresponding log message is this:
![image](https://user-images.githubusercontent.com/52035924/97853973-21891b00-1cf9-11eb-9432-6f17736eda6f.png)
Thank you for your help

**Comment by zagorsky** [comment]
@matalukes I recommend downloading the full Elastic Beanstalk logs (instructions here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html) and looking through the Apache error logs for a stack trace.

**Comment by matalukes** [comment]
@zagorsky Thank you for your recommendation. I downloaded error_log file from /var/log/httpd/ folder in EC2 instance and I saw this error, which was logged over and over:
![image](https://user-images.githubusercontent.com/52035924/98012532-80ce5480-1df9-11eb-9bbb-be140b762f17.png)

So I presume, that Sentry DSN is required for running beiwe. But now i am struggling with format of DSN values from sentry.io. I tried this format:
![Snímek obrazovky 2020-11-03 173215](https://user-images.githubusercontent.com/52035924/98013331-8aa48780-1dfa-11eb-81c3-5a52447cd7ae.png)
but that didn't work.
sentry.io offers these values now:
![Snímek obrazovky 2020-11-03 173533](https://user-images.githubusercontent.com/52035924/98013711-01418500-1dfb-11eb-831a-793c55bb2b29.png)
Of course I can try some possibility formats that came to my mind, but if you can share the correct format, I hope it will be useful for other users as well.

**Comment by biblicabeebli** [comment]
I've removed the images you posted as they contained still-legible credentials.  Please remember rotate any credentials that were in those screenshots.

After seeing what you posted it appears to be the case that Sentry has changed their DSN format... again!  Surprise!  Our deployed systems continue to work and report their errors correctly to Sentry, but I am no longer able to get the old format DSN from the site, even clicking the deprecated DSN button.  Fun!

The development branch is ready for production use.  I am only waiting for the opportunity (This Week, I Hoooope...) to get our production server onto the development branch as a final, final test before moving to production, the code has been on our staging server for..... like....... six months now.  Apologies for the mess....

If you want to try and get ahead of the flood you can check out onto development and do an eb deploy operation from there.  

To deploy a data processing server you need to:
be on the matching branch you want to deploy,
set an environment variable,
pass a flag.
(I haven't gotten around to documenting this.)

```
git checkout development
export DEV_BRANCH="development"
python launch_script.py -dev -create-manager
```

The script will probably exit weirdly, possibly with an error and a stack trace.  If that happens please post the stack trace, but it is very likely a side effect of certain user-unfriendly details enabled by the `-dev` flag

**Comment by matalukes** [comment]
The script ends with this lines, everything else seems to be as same as in previous deploys.
![error_create_worker](https://user-images.githubusercontent.com/52035924/98112047-cfcfc480-1ea1-11eb-9330-f7136ea4cf55.png)
After deploy, I tried http request, but result has remained the same - 500 Internal Server Error. So I checked log files and although I have deployed development branch, error logs are still about DSN. Should I try some DSN formats in master branch or wait for your production update?

**Comment by zagorsky** [comment]
@matalukes yes, you should try a few different DSN formats.  I'm not sure which one works.

**Comment by biblicabeebli** [comment]
Try removing the DSNs from your environment variables... I think it is
saying the format is wrong, the whole thing is skipped if you provide no
values.

**Comment by matalukes** [comment]
Hi, I have finally managed to deploy beiwe-backend on server! On development branch I have deleted lines in config files which exit configuration if DSNs ain't provided and also lines with forwarding DSN variables.
Thank you for all of your help

**Comment by zagorsky** [comment]
@matalukes glad you got it working!

**Comment by roblewis1237** [comment]
@matalukes @zagorsky @biblicabeebli - please could you write up how you resolved this? I'm also having this issue and unfortunately I cannot work out how to resolve it using the `development` branch and removing the DSN variables. thanks!

**Comment by matalukes** [comment]
Hi @roblewis1237 ,
What I have done to beiwe make it work without DSN:
1. git checkout development
2. export DEV_BRANCH="development"
3. In beiwe-backend/config/settings.py: 
Delete rows 27-29
SENTRY_DATA_PROCESSING_DSN = getenv("SENTRY_DATA_PROCESSING_DSN")
SENTRY_ELASTIC_BEANSTALK_DSN = getenv("SENTRY_ELASTIC_BEANSTALK_DSN")
SENTRY_JAVASCRIPT_DSN = getenv("SENTRY_JAVASCRIPT_DSN")

4. In beiwe-backend/cluster_management/deployment_helpers/configuration_utils.py:
Delete rows 151-154
    for name, dsn in sentry_dsns.items():
        if ensure_nonempty_string(dsn, name, errors, beiwe_variables_name):
            if not DSN_REGEX.match(dsn):
                errors.append('({}) Invalid DSN: {}'.format(beiwe_variables_name, dsn))
and delete rows 159-161:
    for key in reference_environment_configuration_keys:
        if key not in beiwe_variables:
            errors.append("{} is missing.".format(key))
5. In the file [YOUR-ENV-NAME]_beiwe_environment_variables.json delete all rows except one with the domain, delete comma too
6. In step when you create manager, add this suffix 
python launch_script.py -dev -create-manager
7. In the beiwe-backend repo, configure the file .elasticbeanstalk/config.yml
replace "master" with "development"

And with this setup, it works for me.

**Comment by biblicabeebli** [comment]
Hello!
All the setup is no longer required, we have officially moved the development branch (with a couple commits of buf fixes and readme updates, onto master.)

There are also some convenient launch script commands to terminate existing servers so you don't have to do that manually.

Thanks for posting the full thing, please post any issues that may come up with the current state of the master branch.

**Comment by roblewis1237** [comment]
@matalukes- thanks a lot for detailing out the steps you took!

And @biblicabeebli- thanks for the new release info, I'll check it out!
