### ISSUE TITLE
Invalid DSN

### ISSUE THREAD

**Issue by litingzhou1** [onnela-lab/beiwe-backend#173]
Hi,

Thank you for sharing your work. I am very interested in it and start to deploy in my local machine. But I met some problems. Like below:
python launch_script.py -create-environment
After I run this command, it shows the error list below:

_ERROR cluster-management: (flourish_beiwe_environment_variables.json) Invalid DSN: https://010d5ba2f3cd4cf9abe5a5232665f1ae@o474755.ingest.sentry.io/5511751
ERROR cluster-management: (flourish_beiwe_environment_variables.json) Invalid DSN: https://010d5ba2f3cd4cf9abe5a5232665f1ae@o474755.ingest.sentry.io/5511751
ERROR cluster-management: (flourish_beiwe_environment_variables.json) Invalid DSN: https://010d5ba2f3cd4cf9abe5a5232665f1ae@o474755.ingest.sentry.io/5511751
ERROR cluster-management: (flourish_beiwe_environment_variables.json) SENTRY_JAVASCRIPT_DSN cannot be empty_

Could you please give me some suggestions? Thanks a lot!

**Comment by biblicabeebli** [comment]
I'm creating a new issue for updating Sentry.io support.
You should now be able to deploy without sentry parameters present with the current code on master.
Regardless, I strongly recommend deploying master and updating all data processing servers to use that branch, it contains a lot of fixes.
