### ISSUE TITLE
'eb init' fails with ERROR: NotFoundError - Platform "64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6" does not appear to be valid

### ISSUE THREAD

**Issue by litingzhou1** [onnela-lab/beiwe-backend#174]
my python version is python3.6.12. The "64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6" appeared when I run the be init'.

**Comment by biblicabeebli** [comment]
You seem to have posted and then closed several issues.
I'm catching up on community involvement and issues, and we just released a big bug fix update.  You can re-post or get in contact with me directly, eli@zagaran.com.
