### ISSUE TITLE
"Follow Step 7 and Step 8 to complete your Beiwe setup and start enrolling participants"

### ISSUE THREAD

**Issue by litingzhou1** [onnela-lab/beiwe-backend#175]
Hi,

Thanks for sharing your work. I met a problem when deploying in when I follow the instruction in "Beiwe deployment extra information for non IT users", I saw "Follow Step 7 and Step 8 to complete your Beiwe setup and start enrolling participants!". But there is no Step 7 and Step 8 showed. Could you please help to check it? Thanks a lot!

**Comment by biblicabeebli** [comment]
uuuuhhhh...

**Comment by biblicabeebli** [comment]
Welp, something must have changed and I'm not immediately sure what it was referring to.
This is documentation is for the very out of date AMI version of the codebase/beiwe server, and there isn't good advice I can give on that for numerous technical reasons.

I know you have posted some issues about setup recently, unfortunately you got us exactly at a transission point.  We are in the process of getting a new AMI runnable, possibly as a single server instance that can be deployed via the launch script.  I'll try and keep you updated, feel free to reach out by email too.

**Comment by biblicabeebli** [comment]
** I sent the previous comment because the section you mentioned is in the AMI section of the directions.
