### ISSUE TITLE
Embedded javascript's automatic conversion of HTML-escaped characters breaks study titles with apostrophes in them

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#18]
Relevant code is on lines 22-26 of the manage_studies template, and somewhere between lines 47-52 of manage_admins.

Embedded page Javascript automatically parses html-escaped characters when it encounters them as if they were the real un-escaped character.  The apostrophe is correctly escaped and embedded in the template on the backend, but the javascript on the page interprets the html-escaped apostrophe as the end of the string.

Solution?
We need to change how this page embeds content for Angular. Using the json deserializer will (should) solve the issue, but it can't be inserted into the code as-is.

Bug behavior: angular breaks on these pages, causes page rendering to fail.

**Comment by biblicabeebli** [comment]
@zagorsky was this never fixed?

**Comment by zagorsky** [comment]
This issue isn't there anymore.  I tested both the ASCII single-quote and the Unicode right single quote mark.
