### ISSUE TITLE
Push Notifications still not showing up and Surveys available all the time

### ISSUE THREAD

**Issue by llebois** [onnela-lab/beiwe-backend#189]
Hi Beiwe Gurus - we are encountering the following bugs across iOS and Android systems as of this morning (3/22) despite deleting the app and redownloading/reregistering new participants this morning:

- push notifications are still not showing up to notify that a survey is now available to be taken
- the surveys are now available to be clicked on and taken at any time, not at the designated scheduled time 

Thanks for your help with this!

**Comment by biblicabeebli** [comment]
When tapping on the notification the iOS app does not push you into the survey, it places you on the main screen and prompts you to take any surveys that are currently active.  Surveys can also be configured to be always available.

How up-to-date is your Beiwe server?  Have you uploaded Firebase push notification credentials to it?

**Comment by justintbaker** [comment]
@biblicabeebli Any updates to this issue?  We are still experiencing issues with push notifications even after all the server updates (including Firebase credentials) you helped us deploy.

**Comment by biblicabeebli** [comment]
Hello, I'll be talking with Josh about your situation at some point soon.

The push notification feature has been heavily tested, and we have confirmed that credentials generated by third parties such as yourself do successfully send messages to correctly enrolled participants.  That's all I've got for you right now.

**Comment by biblicabeebli** [comment]
I know this issue is languishing,  We eventually identified that there is a problem with Image surveys remaining permanent, even when deleted.

**Comment by biblicabeebli** [comment]
Substantially resolved, see recently closed issues on ios repo for more.
