### ISSUE TITLE
SMS Sent/Received Issues 

### ISSUE THREAD

**Issue by kwcarlso** [onnela-lab/beiwe-backend#19]
Hello, 

After looking at our recent text message data (in the past 6 months or so), I've realized that we are getting Sent SMS and Received MMS data but _not_ Received SMS or Sent MMS data. Does that make sense? I've attached a screenshot from an excel sheet as an example. How would you suggest addressing this issue?

![screen shot 2017-06-16 at 3 11 41 pm](https://user-images.githubusercontent.com/23105268/27241289-2c3deac4-52a6-11e7-8f5c-43d7f1ac97cd.png)

Thank you!

Kenzie

**Comment by zagorsky** [comment]
Fixed in Beiwe Android app version 2.1.5.
