### ISSUE TITLE
AngularJS error on /edit_survey

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#20]
Two errors on /edit_survey:

1. Error `$compile:tploadangular-route in ?`; https://sentry.io/onnela-lab/production/issues/298743878/

2. Error `ReferenceError/static/javascript/survey-editor/survey-editor.js in ? error$ is not defined`; https://sentry.io/onnela-lab/production/issues/302468788/

**Comment by biblicabeebli** [comment]
This has no negative effect on the app, is old, and is probably a page loading-time bug where some javascript isn't loaded yet.
