### ISSUE TITLE
Peer Review - Paper Issues

### ISSUE THREAD

**Issue by erik-whiting** [onnela-lab/beiwe-backend#208]
Some issues from my review of the paper. Review is being coordinated [here](https://github.com/openjournals/joss-reviews/issues/3417)

_**Summary:**_ - This is good and ticks all the boxes but I have one note. Are the specs on line 11 - 16 necessary or in the right place? It seems like it interrupts the sentences before and after.

_**Statement of Need**_ - This ticks most of the boxes however I feel like the statement "Many researchers are increasingly advocating a more substantial role for large scale phenotyping as a route to advances in the biomedical sciences" is a claim needing a supporting source.

_**State of the Field**_ - The checklist question for this section is "Do the authors describe how this software compares to other commonly-used packages?" This part seems to be missing or could use some elaboration. You say in the Background subsection that surveys are typically used to study human behavior; is this the closest thing to an alternative to Beiwe in your field? Is there no software kind of like Beiwe? If not, can you make that more explicit?

On a related note, you say Beiwe's collection of raw sensor data is more accurate than the data that could be gathered from an SDK (I assume you mean things like React Native, Xamarin, etc., right?). This leads me to believe there are systems out there collecting data via SDKs . Do these systems exist? If so, can you mention them in the spirit of comparing your software to "other commonly-used packages"?

_**Quality of Writing**_ - The writing quality is excellent, nice work.

_**References**_ - References are good except for my note about citing support for your claim in the Background section (lines 30 and 31)

Tag me if you have any questions, updates, or disagreements! I will update the issue and review checklist accordingly.

**Comment by Tam-Pham** [comment]
I very much agree with @erik-whiting's point regarding the ***State of the Field***. To my knowledge, [Purple Robot](https://github.com/cbitstech/Purple-Robot) is another platform for real-time mobile phone sensor data acquisition. I believe it would be of interest to the readers to learn a little bit more about the differences/similarities between Beiwe and other platforms/software.

**Comment by biblicabeebli** [comment]
- Summary: - This is good and ticks all the boxes but I have one note. Are the specs on line 11 - 16 necessary or in the right place? It seems like it interrupts the sentences before and after.

I am not sure what you are referring to with respect to lines 11-16

**Comment by biblicabeebli** [comment]
I am requesting some review of documentation over on #226, and there has been a bunch of activity on #210.

This post seems like it is slightly higher level from the others, and I'm not totally sure what the distinction regarding "paper issues" is about.  Would appreciate a little bit more context and guidance.

**Comment by erik-whiting** [comment]
@biblicabeebli the "paper" we're referring to is the actual article that will be published in the journal and is located here: https://github.com/openjournals/joss-papers/blob/joss.03417/joss.03417/10.21105.joss.03417.pdf

Notes here are more like the traditional peer review process for scientific journals and they don't really relate to the software per se.

**Comment by erik-whiting** [comment]
Thanks for addressing everything @jponnela, the updates look great. Closing this and updating my review at https://github.com/openjournals/joss-reviews/issues/3417
