### ISSUE TITLE
No connection after cluster deployment

### ISSUE THREAD

**Issue by Iqra840** [onnela-lab/beiwe-backend#219]
Hi!
We have successfully deployed the cluster server several times after following every step of the Scalable Deployment wiki, but each time, there seems to be a persisting issue with the connection (please see attached image). We've set up the SSL certificate, double-checked the security group rules, and added the load balancer forwarding rule( port 443 to 80) as well. Would you have an idea of why this might be happening?

![Screen Shot 2021-07-26 at 8 02 38 AM](https://user-images.githubusercontent.com/54781026/126928825-175aef6a-5a02-4a70-9aca-cf8a8d712792.png)
 Here are the eb_activity and error logs: 
[eb-activity.log](https://github.com/onnela-lab/beiwe-backend/files/6875624/eb-activity.log)
[error_log.log](https://github.com/onnela-lab/beiwe-backend/files/6875632/error_log.log)

**Comment by biblicabeebli** [comment]
Email me at biblicabeiwe at gmail dot com, we can set up a call to debug this, the cloudflare status page is a new and different, and it is masking a pedantic detail of browser behavior.  (and would be valuable on our end to get the experience debugging through that.)

**Comment by Iqra840** [comment]
Looks like the URL is live, it seems that the load balancer rule you mentioned [here](https://github.com/onnela-lab/beiwe-backend/issues/166) needed a couple of hours to set up. So Cloudflare is probably compatible with the browser in this case. Thank you for your valuable time!
