### ISSUE TITLE
Internal Server Error: Client (AWS Region Issue?)

### ISSUE THREAD

**Issue by shuvammishra** [onnela-lab/beiwe-backend#220]
Hello,

We've set up the beiwe-backend, following instructions here [https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment](url). I'm running the Beiwe iOS app on Xcode simulator right now. After I create a study on the Beiwe Web Portal, if I try to add a new participant, I get this error message: 

_The server encountered an internal server error and was unable to complete your request. Either the server is overloaded or there is an error in the application_ (as seen in the screenshot at the end of this post). 

Other Sentry information that might help:

**Error Message**: ClientError: An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.

(We're running this from Hong Kong and in the "Configure your application" step in the beiwe deployment instructions, we used ap-east-1 in the global_configuration.json file.)

```
tocore/client.py in _make_api_call at line 676

        )
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
            raise error_class(parsed_response, operation_name)
        else:
            return parsed_response
    def _make_request(self, operation_model, request_dict, request_context):
        try:


```

**Tags**: 

<img width="858" alt="Screenshot 2021-08-03 at 3 36 55 PM" src="https://user-images.githubusercontent.com/48913852/127976662-fb6c2eb8-72c3-4f8f-98a8-4025e74a9cc3.png">

**Screenshot from Web Portal while trying to add new user to study**

<img width="1440" alt="Screenshot 2021-08-03 at 3 09 24 PM" src="https://user-images.githubusercontent.com/48913852/127974390-d09dcb3c-9337-4021-b917-5fb297ddc2eb.png">

@biblicabeebli any idea on how to go about solving this?

**Comment by biblicabeebli** [comment]
Pretty sure that error means the AWS S3 permissions are not working, Beiwe needs to stick a file onto s3 at Participant creation.

Based on [this](https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/) article S3 service does exist in your region, but you should try and confirm that.

Check the permissions that are associated with the aws credentials associated with the system, make sure you have the s3 credentials.  Let me know how that goes.

**Comment by shuvammishra** [comment]
We redeployed the entire back-end but this time, we used us-east-1 instead of ap-east-1 with no other changes and did not run into the same issue. This might not be the only solution but it is what worked for us!
