### ISSUE TITLE
Empty zip file after downloading data from Beiwe Study Portal

### ISSUE THREAD

**Issue by shuvammishra** [onnela-lab/beiwe-backend#223]
Hello, 

After deploying the backend, I set up a production study and registered myself as a participant for a test run. I have let it run for a few days and I can see the data collected showing up on the participant dashboard. However when I try to download the processed data, it gives me a data.zip file, which when opened, is empty. 

I understand that, _“Researchers will only be able to download processed data output from the Data Analysis Pipeline”_ for production studies. So, I don’t quite understand why the zip file is empty when it shows me that data is being collected on the patient dashboard.

Thanks!

**Comment by shuvammishra** [comment]
Faced the same issue with a test study today as well - empty zip file after downloading processed data. Downloading raw/ chunked data seems to be working fine for both test and production studies.

**Comment by biblicabeebli** [comment]
Hi, sorry about the slow response, I should be more available to help out this week.

Inaccessible data usually means an issue with your data processing server(s).  Have you used the launch script to deploy one?

**Comment by biblicabeebli** [comment]
Closing issue as there was no followup.

**Comment by zagorsky** [comment]
"Processed Data" is Pipeline output data.  But the Data Analysis Pipeline is being deprecated in favor of Forest.  So your Data Analysis Pipeline is probably not running and not producing any output data, and you should stick with downloading raw/chunked data for now.
