### ISSUE TITLE
Error parsing ASCII double-quote character in /edit_survey

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#24]
Error in /edit_survey rendering a survey that has an ASCII double-quote mark in the text of a question.  I think we're scrubbing double-quote marks when the survey gets saved, so I'm not sure how this got in there.

This may be fixed in the django branch.

**Comment by biblicabeebli** [comment]
Codebase has been ported to python3 strings are now native utf, can you test?
