### ISSUE TITLE
Data Downloader 504 Gateway Timeout

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#25]
Description from a research collaborator:

We still run a process to download Beiwe data automatically, and I've been noticing spurious HTTP 504 (Gateway Timeout) errors for a small handful of patients.

 

These have been happening over the course of several months, but not consistently. We might go 2-4 days without seeing one, but then we might have this issue for an entire day. So far I've seen this issue with 4 patients, but two of them  come up much more often: 81hdg39h and 949iuit. 

 

The errors are coming from the same HTTP POST request to get-data/v1 that I've been making for quite a while (haven't touched that part of the code in a while):

 

study: FAS_Buckner_Coombs_SCS_SocialMedia_Internet
patient: 32mfp7wo
datetime of last error: 2018-02-05 02:00:56,924

study:  McLean_Baker_and_Buckner_Circuit_Dynamics_in_Bipolar_Disorder
patient:  949iuit
datetime of last error:  2018-02-02 01:37:21,624

study: McLean_Webb_Examining_Reward_Related_Predictors_and_Mechanisms_of_Change_in_BA_Treatment_for_Anhedonic_Adolescents
patient: 81hdg39h
datetime of last error: 2018-02-02 01:37:53,981

study: FAS_Buckner_Coombs_FLS_InternetGames
patient: 2qsxciot
datetime of error: 2018-02-02 08:01:01,796

Is there anything in the server logs to help troubleshoot. The 504 could mean that the request is never making it to studies.beiwe.org, but it seems to be affecting those two subjects mentioned above (81hdg39h and 949iuit) too consistently.

**Comment by tokeefe** [comment]
Some movement on this issue...

Without passing 'web_form: true' to /get-data/v1 the client won't get a chunked/streamed response. The request just hangs (assuming until the ZIP archive is ready) and this sometimes results in a timeout. 

An issue with always providing 'web_form: true' is that the resulting ZIP archive doesn't include a registry file, which is necessary to request future "delta" downloads (for lack of a better term).

I think this might be at least part of the issue, or the entirety of the issue.

**Comment by biblicabeebli** [comment]
Confirmed bug, reference data access api download script raises same/similar error.

**Comment by biblicabeebli** [comment]
@tokeefe I don't recall whether this issue was ever resolved.
The codebase has been ported to python3 since this issue was created, could you please re-test?

**Comment by tokeefe** [comment]
All of the followup communication for this issue took place over email, but it was fixed. By some miracle I was able to even dig up the commit here https://github.com/onnela-lab/beiwe-backend/commit/1c61a975105a9542682f73a55028bc009d52d150
