### ISSUE TITLE
improve markdown/general layout support on audio survey prompts

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#252]
Our wiki page on markdown has a weird comment about the state of support of markdown on audio surveys, and the beiwe web page should be extended to use a textfield to improve multiline input.

"We can change them to support multi-line prompts; this should be very easy."

https://github.com/onnela-lab/beiwe-backend/wiki/App-Markdown-support

**Comment by amgeronimo** [comment]
Thanks Eli,

In the elastic beanstalk server, i attempted my own fix, changing frontend/templates/edit_survey.html from
 
```
          <input id="voice_recording_prompt_text_input" type="text" class="form-control"
                 value="{% if survey.content[0] %}{{survey.content[0]['prompt']}}{% endif %}">
```

to

```
            <textarea name ="question_text" id="voice_recording_prompt_text_input" class="form-control" rows=4>
                {% if survey.content[0] %}{{survey.content[0]['prompt']}}{% endif %}
            </textarea>
```

This allowed me to type multiline text in the input box.  Some odd behavior -- every time i refesh the survey page, the prompt box switches between single line and multiline.  I do get multiline prompts when the survey is pushed to both IOS and Android.  Markdown formatting only works for android, as documented.

**Comment by biblicabeebli** [comment]
this is long resolved.
