### ISSUE TITLE
read in study config from json file for data analysis

### ISSUE THREAD

**Issue by mariasimoneau** [onnela-lab/beiwe-backend#26]
Some of the data analysis pipeline routines need to be configured with the study settings for how often the sensors are on/off and collecting data & whether or not a sensor is being used.  This is a manual effort now.  In order to reduce errors, it would be good if the routines could pull in these settings for a study.  Perhaps the json file (or just the info) from the "copy study" effort could be used for this?

**Comment by zagorsky** [comment]
We can probably use `/api/data_access_api.py` to implement this

**Comment by biblicabeebli** [comment]
@zagorsky I thought we implemented this?

**Comment by zagorsky** [comment]
I don't remember us implementing this, but let me know if you find it in the codebase.

**Comment by biblicabeebli** [comment]
I have found no documentation about this, and the analysis repo is so out-of-date that I doubt this is being worked on.  I am therefore deprecating this issue.  If it comes up again as part of other pipeline development from newly interested developers or colaborators we can create a new issue.
