### ISSUE TITLE
name of data download file is "v1"???

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#271]
I don't know why, but that is the file name I just got during some testing of python 3.8 deploy.

**Comment by zagorsky** [comment]
@biblicabeebli I think the data download API has `v1` in the URL, although I don't know why that would get copied into the filename.

**Comment by biblicabeebli** [comment]
The code is `filename="data.zip".
I've confirmed in the django code that the parameter is "filename".
Wat.

**Comment by biblicabeebli** [comment]
bug is fixed on branch fix-download-filename.
