### ISSUE TITLE
HTTP 400 Bad Request errors from the web portal

### ISSUE THREAD

**Issue by ruzicll** [onnela-lab/beiwe-backend#279]
Hello. We have a "scalable deployment" in AWS that has occasionally had celery issues and needed `launch_script.py -terminate-processing-servers` and then `-create-manager`. The last time we did this before the update to python 3.8 survey notification was restored but the web portal became inaccessible with `Bad Request (400)` messages. Attempting to download data using [lochness](https://lochness.readthedocs.io/en/latest/) generates the same error. This persists after having gone through the python 3.8 update steps.

The only thing I've seen that I recognize as out of place so far (and there could be plenty I wouldn't recognize) was that when I tried to follow advice from [another issue](https://github.com/onnela-lab/beiwe-backend/issues/51#issuecomment-521722655) to "check if the database / database shell is accessible," I found no /opt/python directory. (There is such a directory on the old eb server.)

Any ideas on how to fix this or what to look at to narrow down the problem?

***

Edit: Actually the last time trying creating a manager before the update did NOT work, perhaps due to trying `git pull` on `main` without going through the update steps. It was using the `python-3.6` branch, as advised by @biblicabeebli, that got through `-create-manager` without errors, started survey notifications again, and introduced the HTTP 400 error.

**Comment by biblicabeebli** [comment]
Seen, will try and get into this soon.

0th question: Are you getting all 400 errors when accessing the website? If so that sounds like your browser is trying to hit the backend via http, not https.

I don't know about lochness' runtime details, there's not currently an http-to-https redirect, which was an optional-ish detail of the 3.6 era.

**Comment by ruzicll** [comment]
Since the first time the HTTP 400 error appeared, I have not seen the web portal, only the error, if that is what you're asking.

Not sure if this is relevant, but https://\<address\>—implicitly or explicitly in the address bar—works (brings up the error) but if I manually enter http://\<address\> I end up with my ISP's search page.

**Comment by biblicabeebli** [comment]
(The ISP thing - that is a junk ISP problem, ISPs can and do inject garbage into insecure connections.  It is bad and dumb, but not diagnostic.)

Coupla things to check:
- does your DOMAIN_NAME environment variable actually match your url?  The value should not include `https://`, it is usually something like `my_weird_subdomain.example.biz`
- check if you are forwarding to port 443 to port 80 for the load balancer's SSL settings, that is conceivably a cause; maybe.  Getting last-leg-encryption is not functional yet on the 3.8 platform, the software stack changed too much.
- could you please post a screenshot of the error?  I'm looking to see if it is a totally generic 400, or if there is any formatting applied. (this tells me something about which layers of the webserver are involved)

**Comment by ruzicll** [comment]
The DOMAIN_NAME is _not_ correct. It might be a C name (we have two) that was redundantly pointing to the old A record? As in not the one we used, but a valid one nonetheless. (However this problem cropped up before the python 3.8 update.)
After changing it, what needs to happen for it to take effect?

Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port | ...
-- | -- | -- | -- | --
HTTPS | 443 | HTTP | 80 | ...

Screenshot:
<img width="574" alt="new" src="https://user-images.githubusercontent.com/77860738/153693092-5f230776-5c71-4b79-a71c-097d1ce71277.png">

I can still get our previous server from its A record and it's still the same error but the font size is different:
<img width="573" alt="old" src="https://user-images.githubusercontent.com/77860738/153693112-4804a4b0-bea5-488d-8963-b77695c095f4.png">

**Comment by biblicabeebli** [comment]
Yeah that's the generic error, pretty positive you are hitting the DOMAIN_NAME issue.

Go here on the AWS console, click edit, change the domain name to match the one that is on the ssl certificate in use on the load balancer, then click apply.  (This is in the elastic beanstalk view of, in this case, our production instance.)
![Screenshot_20220211_225218](https://user-images.githubusercontent.com/1715982/153695600-bdb2ff92-2020-45ce-89a5-67fe942c48cf.png)

I recommend changing the value in your configuration files to match the domain as well. I don't think any behavior of data processing servers _currently_ depends on it, but that could change and the value is expected to be correct.

General background on why this is happening:
This value is passed in as part of a security detail of the (newish) Django-based webserver runtime.  The old Flask server did not have this detail.  The python-3.6 branch includes the Django backend, the python-3.8 branch includes only the updated infrastructure details to work on the "AWS Python 3.8 Platform" plus some code compatibility changes.  It should be feature-identical (and bug-identical) to the python-3.6.  Definitely update to `main` once the server is accessible from the 3.8 branch, there are features and bugfixes.

**Comment by biblicabeebli** [comment]
(Let me know if there are any remaining issues, I will close this as needed, I want to review it and potentially update documentation.)

**Comment by ruzicll** [comment]
That works!

Follow-up: Is missing data to be expected given that it has been in this state for a while? And/or Is it safe to assume that whatever data is recoverable will be recovered automatically? (Is it a problem that there's still no /opt/python on the new EB server?)

Thanks as always for your help!

**Comment by biblicabeebli** [comment]
Devices upload their data best-effort, don't delete anything until it is uploaded.  You will probably have a surge of uploads, make sure your data processing server is functional and it will catch up.

**Comment by ruzicll** [comment]
Some of the data I was looking for is missing for unrelated reasons. This all is looking good! 

Thanks again!

**Comment by nelsonroque** [comment]
Hi @biblicabeebli thank you for all your efforts and time! 

I'm running into a similar issue ([following the cluster deployment instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment)).

I am getting either a 403 (if no date provided) or a 400 if all values provided when downloading data for either a test study or production data study (Screenshots below). 
![Screen Shot 2022-03-10 at 12 53 29 PM](https://user-images.githubusercontent.com/1222883/157725031-65a81f3e-4b3f-412b-9003-517829c22304.png)
![Screen Shot 2022-03-10 at 12 52 30 PM](https://user-images.githubusercontent.com/1222883/157725060-75263abc-c04d-4bdf-96af-f36818143252.png)

I double-checked the env var for the server URL and it does not have https (as noted above). I also checked to see if the load balancing ports match up with the above (they do). The [celery troubleshooting instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Celery-troubleshooting) were helpful, but nothing seems to be out of line there

Any information on aspects to check would be greatly appreciated! Thank you for your help and time!

**Comment by biblicabeebli** [comment]
@nelsonroque I've made a new issue, I am closing this issue.
