### ISSUE TITLE
400 class errors on data download

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#283]
Hi @biblicabeebli thank you for all your efforts and time! 

I'm running into a similar issue ([following the cluster deployment instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment)).

I am getting either a 403 (if no date provided) or a 400 if all values provided when downloading data for a test study (Screenshots below). 
![Screen Shot 2022-03-10 at 12 53 29 PM](https://user-images.githubusercontent.com/1222883/157725031-65a81f3e-4b3f-412b-9003-517829c22304.png)
![Screen Shot 2022-03-10 at 12 52 30 PM](https://user-images.githubusercontent.com/1222883/157725060-75263abc-c04d-4bdf-96af-f36818143252.png)

getting a 404 for processed/pipeline output
![Screen Shot 2022-03-10 at 12 58 13 PM](https://user-images.githubusercontent.com/1222883/157725792-21939296-4b1a-4b79-a355-c3c780ca8739.png)

I double-checked the env var for the server URL and it does not have https (as noted above). I also checked to see if the load balancing ports match up with the above (they do). The [celery troubleshooting instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Celery-troubleshooting) were helpful, but nothing seems to be out of line there

Any information on aspects to check would be greatly appreciated! Thank you for your help and time!

_Originally posted by @nelsonroque in https://github.com/onnela-lab/beiwe-backend/issues/279#issuecomment-1064339922_

**Comment by biblicabeebli** [comment]
@nelsonroque  Hello!
The pipeline page is gone, the 404 is correct.  If you were using it.... then I believe you were the only person doing so?

I have a guess about the other two, which is (should be) currently fixed on the website-improvements branch (nearly ready to deploy, do not deploy it if you have pipeline data!).  My guess is that you are a site admin but have not added yourself to the study.  Once you do so you should be set.

The 403 and 400 error cases are contained in `authentication/data_access_authentication.py`.  Its quite legible, you will see the options.
If you want to debug directly you can set
`DEBUG_API_AUTHENTICATION = True`
then check the logs in `/var/logs/messages`
(you can `git add authentication/data_access_authentication.py` to get it staged, then `eb deploy --staged` to deploy, then git reset without ever committing.)

The time range parameters are not required fields, so if you could please double check that detail for me. That is a separate bug if its presence changes the return code.

**Comment by biblicabeebli** [comment]
Are your issues resolved? (reviewing issues for closure)

**Comment by nelsonroque** [comment]
Yes, a fresh deployment solved the issue here. Thank you for your help and time!

**Comment by biblicabeebli** [comment]
awesome, feel free to get in touch in anything comes.
