### ISSUE TITLE
Survey Notification "Request contains an invalid argument"

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-backend#291]
iOS users of my Beiwe deployment have had survey notification errors as of 8/2/22.  Not (yet?) affecting android users of Beiwe2 app. 
![image](https://user-images.githubusercontent.com/30633702/182656398-4fd851db-9352-4192-81ac-70993676b8f3.png)

**Comment by biblicabeebli** [comment]
Apologies anyone reading for my slow response, the beiwe2 ios app was transferred between apple developer accounts and this screwed up push notification credentials.  I have a new build of the app with functional push notifications, I'm now testing on testflight, will get the app onto the app store asap.

**Comment by biblicabeebli** [comment]
error message should now state "Auth error from APNS or Web Push Service". (this error is correct, "Request contains an invalid argument" is... its just insanely incorrect and makes no sense at all, not that Any of the firebase errors contain useful information.)

**Comment by amgeronimo** [comment]
Confirmed -- started getting that error mid-day 8/5

**Comment by biblicabeebli** [comment]
Closing, remaining issues with testflight push notifications are unrelated.
