### ISSUE TITLE
Error: Policy has invalid resource (while configuring the application)

### ISSUE THREAD

**Issue by AresCao0314** [onnela-lab/beiwe-backend#293]
Hello,
I'm trying to deploy Beiwe using [link](https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment)
while I was configuring the application.
try to create environment
python launch_script.py -create-environment
and I got below error:
botocore.exceptions.ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource
I check the AWS console, it has the database created, but I guess the environment is not created successfully.
Could anyone suggest how to solve this issue?

Below is the Traceback:
```
INFO cluster-management: Database status is no longer 'creating', it is 'available'
INFO cluster-management: checking availability of bucket name 'beiwe-data-dlab-c0enrmbzsejnd2k2fkwalm2ecxvplgkoqnhw98uyhroy6wd'
Traceback (most recent call last):
  File "/Users/caochenlong/Documents/GitHub/beiwe-backend/cluster_management/launch_script.py", line 635, in <module>
    do_create_environment()
  File "/Users/caochenlong/Documents/GitHub/beiwe-backend/cluster_management/launch_script.py", line 372, in do_create_environment
    create_finalized_configuration(name)
  File "/Users/caochenlong/Documents/GitHub/beiwe-backend/cluster_management/deployment_helpers/configuration_utils.py", line 236, in create_finalized_configuration
    config["S3_BUCKET"] = create_data_bucket(eb_environment_name)
  File "/Users/caochenlong/Documents/GitHub/beiwe-backend/cluster_management/deployment_helpers/aws/s3.py", line 76, in create_data_bucket
    s3_require_tls(name)
  File "/Users/caochenlong/Documents/GitHub/beiwe-backend/cluster_management/deployment_helpers/aws/s3.py", line 60, in s3_require_tls
    s3_client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(bucket_policy))
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/client.py", line 401, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/botocore/client.py", line 731, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource
```

**Comment by biblicabeebli** [comment]
Whelp, applying the bucket policy failed but it does not give a reason, fun.

What region are you deploying in? Historically S3 was not created equal or even missing from some regions.  That policy was updated to include a second layer of aws-applied encryption iirc, so maybe it is that?

**Comment by AresCao0314** [comment]
> Whelp, applying the bucket policy failed but it does not give a reason, fun.
> 
> What region are you deploying in? Historically S3 was not created equal or even missing from some regions. That policy was updated to include a second layer of aws-applied encryption iirc, so maybe it is that?

Hello, thanks for your reply.
I'm deploying at "AWS_REGION": "cn-northwest-1", it's an AWS data center in China (in Ningxia Province).
Do you think the solution could only be changing AWS data center to another region, or could you suggest some other method to overcome this?

Many thanks.

**Comment by biblicabeebli** [comment]
dev reference, related commit: https://github.com/onnela-lab/beiwe-backend/commit/4c570b48629de018b0b16492b64f377dde78b99c

Well, I guess it tracks that for some reason encryption is different there, I wish the error message was better.
Fortunately these enhancements are somewhat redundant, the data stored on s3 (and consequently the data in transit) is already encrypted by the Beiwe-backend.  It will be your call on whether that is adequate / legally viable for your useage.

Two solutions:
- try a different region
- comment out lines 75 and 76 in cluster_management/deployment_helpers/aws/s3.py
- these lines: https://github.com/onnela-lab/beiwe-backend/blob/e28384c195d9e511e52c8f807a425ef97b1ea622/cluster_management/deployment_helpers/aws/s3.py#L75-L76

Please let me know which option you go with or if this still doesn't work so I can close the issue.

**Comment by biblicabeebli** [comment]
Were you able to determine if the problem was regional?  If so I would like to close this issue.

**Comment by biblicabeebli** [comment]
closing thhis issue
