### ISSUE TITLE
"Unable to assume role" IAM error on eb deploy

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#31]
Error report from Zhe:
> in the "Setup AWS EB CLI" section of the wiki, the command `eb deploy` does not work because the elastic beanstalk server's health is reported as "severe" and the server state is not "ready" for deployment. The one error reported by the server is:
        Unable to assume role "arn:aws:iam::[NUMBER]:role/arn:aws:iam::[NUMBER]:role/beiwetest-elasticbeanstalk-service-role". Verify that the role exists and is configured correctly.
        My investigation shows that I do indeed have an IAM role with the address `arn:aws:iam::[NUMBER]:role/beiwetest-elasticbeanstalk-service-role`. However, my guess it that there is a typo in the ELB server configuration? I'm not familiar with AWS, but if you look closely at the error message, could it be that the ELB server is looking for a role that has the prefix pasted twice?

**Comment by biblicabeebli** [comment]
Pretty confident that this is a clone of issue 32, https://github.com/onnela-lab/beiwe-backend/issues/32

**Comment by mmendivilg** [comment]
I had this same problem, to fix it I just created a new role, instead of using the default role option.

template.yml:

    AWSTemplateFormatVersion: '2010-09-09'
    Description: CloudFormation template to create a service-linked role for Elastic Beanstalk
    
    Resources:
    
      ElasticBeanstalkServiceRole:
        Type: 'AWS::IAM::Role'
        Properties:
          RoleName: 'cicd-role'
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'sts:AssumeRole'
                Principal:
                  Service: 'elasticbeanstalk.amazonaws.com'
          Description: 'Allows Elastic Beanstalk to create and manage AWS resources on your behalf.'
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk
            - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
            - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
    
    Outputs:
      RoleArn:
        Description: 'ARN of the Elastic Beanstalk service role'
        Value: !GetAtt [ElasticBeanstalkServiceRole, Arn]

***Or in the aws Management Console:***

* Roles > Create
* Trusted entity type > AWS service
* Use case > Elastic Beanstalk
* (Everything else as default)
* Create

lastly:
`eb create $EB_CONFIG-env --platform "$EBS_PLATFORM" --service-role $EB_SERVICE_ROLE`

**Comment by biblicabeebli** [comment]
@mmendivilg what did you do that caused this issue to occur?

**Comment by mmendivilg** [comment]
I Basically built a docker image and pushed it to aws ecr and deployed to elastic beanstalk without specifying the iam role in the process. the health report immediately showed this warning:

Unable to assume role <role> Verify that the role exists and is configured correctly.

Steps to reproduce the error:

```
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region us-west-2
ECR_PASSWORD=$(aws ecr get-login-password --region us-west-2)
echo "$ECR_PASSWORD" | docker login --username AWS --password-stdin $ECR_ENDPOINT
docker build -t simple-nginx -f Dockerfile.nginx .
docker tag $DOCKER_TAG_NGINX $ECR_ENDPOINT/$DOCKER_TAG_NGINX
docker push $ECR_ENDPOINT/$DOCKER_TAG_NGINX
eb init $EB_CONFIG -r us-west-2 --platform "Docker"
# eb create $EB_CONFIG-env --platform "$EBS_PLATFORM" # Only necessary for the first time
eb deploy $EB_CONFIG-env --region us-west-2
```

**Comment by biblicabeebli** [comment]
Could you possibly post your Docker file, and put your instructions here along side it?
Its not Onnela Lab's usage, but I acknowledge we have an older technical stack and many people are expecting containers these days.

Make a new issue with it, I will find a place to add it to the repo. (I'm thinking `cluster_management` but I'm not sure. I'd like to have a documentation page about ECR setup.)
