### ISSUE TITLE
[Android] notifications not clearing / multiple survey submission

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-backend#316]
participants have been reporting that surveys on a relative time schedule (7/14/28 days after start date) are not clearing from their android phone notifications once submitted.  This means I am getting multiple different submissions of text and audio surveys when i am only expecting one per week/month.

**Comment by biblicabeebli** [comment]
(Woops, missed this)

Can you please provide the exported json study settings? You can export them from the edit study page.
A screenshot of an affected user's push notification history might also help.

If you have confidentiality concerns about posting either of those on the github thread you have my email.

**Comment by biblicabeebli** [comment]
I have received your out-of-band communication

Do you have a date when this started? We had a June 2nd and July 5th releases.

**Comment by biblicabeebli** [comment]
Update: there is definitely something going on that is strange, current guess is a detail of the server-derived push notification survey schedules vs the device-local survey schedules.

(Could be a timezone bug.)

**Comment by amgeronimo** [comment]
I haven't been getting any more reports of the issue.  It seems to have
temporarily fixed itself

**Comment by biblicabeebli** [comment]
updating title

**Comment by biblicabeebli** [comment]
Well I've gone ahead and put some effort into getting the timezone from the device (currently just on Android) for use in sending push notifications at the appropriate time of day. It's functional, it has a test, but its not going to be ready for immediate release.

The work isn't even necessarily correct yet, like do we actually desire timezone shifting for absolute surveys no idea.

Backend work is on the `participant-timezones` branch, android work is on `more-device-info`.

**Comment by biblicabeebli** [comment]
There is an Android app update that begins a possible resolution of this issue, but only on the axis of this being a possible time zone inconsistency issue.

App version 3.5.1 includes updates for Android 13, which includes a new permission about notifications. I don't believe this will be relevant, but it does update the code that tests which permissions have been applied to the app, which Can Help Some Things.
Mostly the update now provides the backend with the device's timezone. Backend support for using this value is not currently enabled, we still have to test that on real devices.  There are tests for the prospective code that I am moderately confident in.

THER IS a slightly possibly relevant bugfix, which is that the main app screen now updates its layout more aggressively, which does solve several bugs.

**Comment by biblicabeebli** [comment]
fwiw I'm currently trying to resolve a who-wrote-this-code-its-terrible-was-it-me?-it-was-me bug on iOS involving many survey responses getting submitted.

**Comment by hydawo** [comment]
We have been testing for this specifically and have not seen this in any of our testing over the past 4 weeks. We've also had external study teams test for this and they have not seen this issue across multiple versions of Android or iOS.

I am closing this issue. Eli knows what caused this issue briefly.

**Comment by biblicabeebli** [comment]
archiving this issue, new issue https://github.com/onnela-lab/beiwe-discussions/issues/220 either is this issue or is a new one and has better information.
