### ISSUE TITLE
Minimum password length is greater than the default_admin login

### ISSUE THREAD

**Issue by demarrid** [onnela-lab/beiwe-backend#319]
When trying to log in with `default_admin` and `abc12`3, the user keeps getting the `500 Internal Server error`. Sentry logs reveal that `ValidationError: {'password_min_length': ['Ensure this value is greater than or equal to 8.']}` is thrown every time a user tries to log in. We've been looking into ways to bypass this, including making our own migrations (though we're not entirely sure how that works) which have been unsuccessful, and we've also looked into changing Django's minimum password length requirement but we're not sure what files that should be done in. Any help on the issue would be greatly appreciated and let me know if any more information is needed (this is my first time opening an issue on GitHub so I apologize if I've broken convention).

**Comment by biblicabeebli** [comment]
Oooo, ok that's definitely a bug, I will have to update the default password to fix thus, and its documentation.

For now do the following:
- ssh onto either the data processing or elastic beanstalk server.
- run `db`, this will drop you into an ipython shell with db access.
- run this:
```
r = RESEARCHER("default_admin")
r.set_password("insert some decent password here")
```
And then try to log in using that password. (The set password function throws errors if the password is not sufficiently complex / long, but the error message should be comprehensible when that happens. Do a number, an upper case, a lower case, and a special char, min length 8.)

**Comment by biblicabeebli** [comment]
My fast attempt at a fix didn't work, I will need to come back to this. pinning issue so it is discoverable.

**Comment by biblicabeebli** [comment]
This may have been resolved when trying to replicate an unrelated issue.... if so please let me know.... I will retest.... eventually....

**Comment by biblicabeebli** [comment]
I'm unpinning this issue in favor of another deploy bug.

It was reported that just changing the password to something with more characters works.  I'm going to push an update with such a change to staging.  I need to find the documentation and update it too...

**Comment by biblicabeebli** [comment]
This has been documented on https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-Instructions---Scalable-Deployment
