### ISSUE TITLE
Add buttons to download some summary statistics (json) to the website - task view

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#333]
There are currently no ways to download summary statistics data that are exposed on the website.

We should have...
time range
Checkboxes: data quantity. oak, jasmine, willow, sycamore

**Comment by biblicabeebli** [comment]
We have an implementation of something viable that covers the idea as proposed here. No checkboxes though so maybe I've misinterpreted. Screenshot below contains example of a link to click on to download a run's data.

Technically it downloads the most current data, not necessarily data associated with that run explicitly, but we could actually build that - it would exclude data overwritten on the participant by other runs of that Forest tree that are more recent.

![image](https://github.com/onnela-lab/beiwe-backend/assets/1715982/ea2bd7de-9ad2-491c-b438-f59bc823f115)

@hassan If this feature request was to create a link to download all participants' forest tree data in a csv, such a request is for a 3-dimensional dataset in a 2 dimensional data format. (columns are forest field names, rows are participants, dimension Z is participant data by date) That seems dumb so I just didn't interpret it that way.

We could still build a button to get all such data in one click, but there are several different solutions to support that goal and it needs more direction than this issue currently contains.

**Comment by biblicabeebli** [comment]
deploying this to our staging server

**Comment by biblicabeebli** [comment]
This may have been developed in error, but it's still useful so I say we keep it.

**Comment by hydawo** [comment]
Done, closing.
