### ISSUE TITLE
make a button to download Summary Statistics data

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#347]
@hydawo add details to this issue of the form and ... the way the data is bundled of summary statistics data.

**Comment by hydawo** [comment]
@biblicabeebli here is a sample file with only headers

This is the CSV that is created when we run our "data_volumes_and_summaries" script (https://github.com/onnela-lab/beiwe/blob/master/code/forest_mano/data_volume_summaries_template.ipynb)

[sample_data_volume.csv](https://github.com/onnela-lab/beiwe-backend/files/14212097/sample_data_volume.csv)

**Comment by biblicabeebli** [comment]
done
- see https://github.com/onnela-lab/beiwe-backend/issues/354

**Comment by hydawo** [comment]
I mistakenly uploaded the wrong file on #354, please use this file:

[sample_data_volume.csv](https://github.com/onnela-lab/beiwe-backend/files/14212097/sample_data_volume.csv)

**Comment by biblicabeebli** [comment]
Ok, the button has been updated, it now downloads ALLLL the summary statistics.

Column names and order are somewhat different, requires review.

**Comment by hydawo** [comment]
Done, reviewed, closing issue.
