### ISSUE TITLE
Error in eb deploy

### ISSUE THREAD

**Issue by yh0903** [onnela-lab/beiwe-backend#351]
Hi, while running the "eb deploy" command, an error occurred in line 59 of the scripts/process_ios_no_decryption_key.py file:

code:
> decrypt_and_upload(generic_events_to_process())

error message:
ProgrammingError: relation "database_genericevent" does not exist
LINE 1: ...cevent"."note", "database_genericevent"."id" FROM "database_...
                                                             ^

Could I have some insights on how to solve this issue?

Thanks

**Comment by biblicabeebli** [comment]
That's a django database error - the database schema doesn't match the expectations of the code.
The code to change the schema in django is via a migration, the migrations are all in `database/migrations`.

Migrations are checked, and if there are any new migrations it runs it. If it can't run the migration you will get weird errors. This looks like something is weird after you have deployed successfully - which is very strange/unlikely.

So first, just deploy to the webserver again using the `eb deploy` command and see if that fixes it.

You can run them manually or debug them by sshing into the data processing server, or use `eb ssh` command to ssh onto the web server - you have to ssh using your private deployment key, and you may need to manipulate open ports via the security groups be able to connect. That's on you.

Once you are in there I can help you debug, I need the output of the following command:
```
python manage.py showmigrations
```

Documentation on migrations can be found here: https://docs.djangoproject.com/en/3.2/topics/migrations/

**Comment by biblicabeebli** [comment]
I'm going to close this issue as there has been no followup and my response was pretty comprehensive.
