### ISSUE TITLE
boto3 ClientError: An error occurred (InternalError) when calling the PutObject operation

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#36]
We got our first S3 error since upgrading from `boto` to `boto3`:

**On the staging server, which is using `boto3`**, we got this error on May 16 at 9:35:20 AM UTC:
`ClientError: An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): We encountered an internal error. Please try again.`
https://sentry.io/onnela-lab/staging/issues/557374729/

**On the production server, which is using `boto`**, we got this error on May 16 at 9:36:54 AM UTC:
`BotoServerError: 500 Internal Server Error <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>`
https://sentry.io/onnela-lab/production/issues/557376411/

**Both of these happened during a 4-minute period when AWS had errors with S3.**  According to a post on status.aws.amazon.com on May 16th:
> *3:32 AM PDT Between 2:35 AM and 2:39 AM PDT, we experienced elevated error rates for requests in the US-EAST-1 Region. The issue has been resolved and the service is operating normally.*

**Comment by zagorsky** [comment]
It looks like the correct behavior happened here on the staging server: boto errored, so the staging server returned a 500 error to the app that was trying to upload the file, which means the app would have kept the file around and tried to upload it later.  The file that failed to upload did successfully get uploaded to the S3 bucket about 30 minutes later, which makes sense, because the study the phone is enrolled in has data upload set to every 30 minutes.

**Comment by biblicabeebli** [comment]
ooo, it happened again and
http://status.aws.amazon.com appears to be down or extremely slow.

**Comment by zagorsky** [comment]
This was a transient error that happened with AWS downtime, and the system handled it correctly (it didn't lose a file).

It would be nice to add code to make this error message more descriptive, but that's not a high priority right now.
