### ISSUE TITLE
Issue with deploying backend

### ISSUE THREAD

**Issue by zadking** [onnela-lab/beiwe-backend#363]
Hi, I am having issues with deploying the backend. Here is the error message I got from the eb logs:

<Message>User: ****/us-east-2-cstore-role/elasticbeanstalk-aws is not authorized to perform: kms:Decrypt on the resource associated with this ciphertext because the resource does not exist in this Region, no resource-based policies allow access, or a resource-based policy explicitly denies access</Message>

If you have any information that might help, that would be greatly appreciated.

Thanks

**Comment by biblicabeebli** [comment]
The string 'cstore' does not appear anywhere in the codebase.

KMS is AWS' key management service, which I think we only use in relation to running on encrypted block storage, which is automatic.

The error you are getting means that the aws regional datacenter us-east-2 in Ohio does not support the service you are hitting. That seems extremely wrong.

I don't know what's going on, I'm gonna need you to provide a lot more context about where you are in the deploy process and what you are trying to do t that causes this to occur.

**Comment by biblicabeebli** [comment]
Are you having this issue anymore? If not I want to close the issue.

**Comment by biblicabeebli** [comment]
I am closing this issue.
