### ISSUE TITLE
Ubuntu LTS release is on April 25th, 2024

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#369]
The tracking issue for upgrading from 18.04 to 23.10 on the data processing servers was
- https://github.com/onnela-lab/beiwe-backend/issues/331
- this work will be merged into staging and main soon, Onnela Lab is currently dogfooding it.

We are currently on 23.10 for the short term, there is no _urgent_ need for system admins to upgrade, these processing servers are not accessible from the internet and so in terms of security they offer virtually zero threat surface.

We will upgrade to 24.04 when we have a free minute after it's release (and usually it's good to wait a couple weeks, plus AWS might not have it day-of).

**Comment by hackdna** [comment]
It is out now: https://releases.ubuntu.com/noble/

**Comment by biblicabeebli** [comment]
No changes other than the target ubuntu server image thing were required, will sit on our staging server for a bit but am anticipating no issues.
