### ISSUE TITLE
get_security_group_by_name does not find the group if the VPC is not default

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-backend#39]
I'm follwoing **Deployment instructions** and faced issues running this command:
`$ python launch_script.py -create-environment`
I created a new VPC which Amazon does not allow the user to set it as default. When I ran this command, it throws an exception saying the security group is not found. After running the code on debug mode I found that it still trying to find the sg group by name that referenced to the default VPC. If I use the default VPC, it successfully creates the environment. From Amazon and other communities I found similar solution:

`Security Group Does Not Exist in VPC`
`Verify that the security group exists in the VPC that you specified. If the security group exists, ensure that you specify the security group ID and not the security group name. For example, the AWS::EC2::SecurityGroupIngress resource has a SourceSecurityGroupName and SourceSecurityGroupId properties. For VPC security groups, you must use the SourceSecurityGroupId property and specify the security group ID.`

https://forums.aws.amazon.com/thread.jspa?threadID=158709
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/troubleshooting.html

**Comment by biblicabeebli** [comment]
The Default VPC is the VPC that AWS creates for you, one in each particular
region. it cannot be changed and it has some configuration details that
dictate numerous qualities of server instances and other AWS entities spun
up within it.

Usage of the default VPC in the chosen region is currently a requirement
for exactly this reason you have encountered here.  Random unexpected
problems like this showed up everywhere during development of the cluster
management code on non-default VPCs. Solving this particular
incompatibility will not be the only incompatibility you would have to deal
with.

It MAY be the case (but based on that documentation you linked to I
somewhat doubt it) that the issue you are encountering could be resolved by
setting up a differently configured VPC with identical options to that of
the default VPC.  However, this means interacting with networking
fundamentals, and is a support nightmare.

**Comment by benazir0** [comment]
It's not needed anymore, so I'm closing it.
