### ISSUE TITLE
Export participant table as csv button

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#393]
- This issue is related to https://github.com/onnela-lab/beiwe-backend/issues/354

This feature request's  utility is pretty obvious. Take the machinery that is on the `view_study` page, plop the table into a csv, download it. Add a button to do that.

Default ordering on this one is going to be by participant id.

**Comment by biblicabeebli** [comment]
(original came in from interfacing with clients and was on our internal tracker, this public issue supercedes that.

**Comment by biblicabeebli** [comment]
This IS actually listed in the mega issue, there was just a wall of text.

**Comment by biblicabeebli** [comment]
@hydawo This feature is awaiting your feedback.

**Comment by hydawo** [comment]
Done, reviewed, closing - HD
