### ISSUE TITLE
/bin/bash: /homeubuntuserver_setup.log: Permission denied

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-backend#40]
I'm follwoing Deployment instructions and I'm stuck at running this command:
`$ python launch_script.py -create-manager`

It's throwing this exception:

> [52.64.88.249] run: # waiting for ssh to be connectable...
> [52.64.88.249] run: echo >> /home\ubuntu\server_setup.log
> 
> Fatal error: run() received nonzero return code 1 while executing!
> 
> Requested: echo >> /home\ubuntu\server_setup.log
> Executed: /bin/bash -l -c "echo >> /home\ubuntu\server_setup.log"
> 
> [52.64.88.249] out: /bin/bash: /homeubuntuserver_setup.log: Permission denied
> Aborting.
> [52.64.88.249] out: 
> 
> Traceback (most recent call last):
> 	, line 540, in <module>
> 	    do_create_manager()
> 	 line 371, in do_create_manager
> 	    configure_fabric(name, public_ip)
> 	, line 78, in configure_fabric
> 	    run("echo >> {log}".format(log=LOG_FILE))
> 	, line 687, in host_prompting_wrapper
> 	    return func(*args, **kwargs)
> 	, line 1090, in run
> 	    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
> 	, line 954, in _run_command
> 	    error(message=msg, stdout=out, stderr=err)
> 	, line 358, in error
> 	    return func(message)
> 	, line 54, in abort
> 	    raise env.abort_exception(msg)
> __main__.FabricExecutionError: run() received nonzero return code 1 while executing!
> 
> Requested: echo >> /home\ubuntu\server_setup.log
> Executed: /bin/bash -l -c "echo >> /home\ubuntu\server_setup.log"
> 
> Process finished with exit code 1

Please help

**Comment by biblicabeebli** [comment]
This is an SSH issue, the server is not appropriately connectable.
Unfortunately the error message (permission denied) is too generic for me
to conclude anything specific.

However, it looks like you posted another issue about security groups
interacting poorly with a non-default VPC.  This sounds like an interaction
with that, check if the ssh port is not opened on this server (check its
security groups).

**Comment by benazir0** [comment]
Hi, the problem was in directory path. I was using Windows 10, therefore, the program is getting windows file path rather than linux file path 

> Requested: echo >> **/home\ubuntu\server_setup.log**
> Executed: /bin/bash -l -c "echo >> **/home\ubuntu\server_setup.log**"

I replaced '\\' on the filepath with '/', but I still get a different error. So I am using Mac now.

I'm stuck here:

> $ python launch_script.py -create-manager

> ............................
> [52.65.164.228] run: /home/ubuntu/.pyenv/shims/pip install --upgrade pip >> /home/ubuntu/server_setup.log
> [52.65.164.228] run: /home/ubuntu/.pyenv/shims/pip install -r /home/ubuntu/beiwe-backend/Requirements.txt >> /home/ubuntu/server_setup.log
> [52.65.164.228] put: /Users/NetfrontDev/beiwe/beiwe-backend/cluster_management/environment_configuration/beiwe-netfront2_remote_db_env.py -> /home/ubuntu/beiwe-backend/config/remote_db_env.py
> Traceback (most recent call last):
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
>     main()
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/Users/NetfrontDev/beiwe/beiwe-backend/cluster_management/launch_script.py", line 540, in <module>
>     do_create_manager()
>   File "/Users/NetfrontDev/beiwe/beiwe-backend/cluster_management/launch_script.py", line 377, in do_create_manager
>     push_manager_private_ip(name)
>   File "/Users/NetfrontDev/beiwe/beiwe-backend/cluster_management/launch_script.py", line 91, in push_manager_private_ip
>     ip = get_manager_private_ip(eb_environment_name)
>   File "/Users/NetfrontDev/beiwe/beiwe-backend/cluster_management/deployment_helpers/aws/elastic_compute_cloud.py", line 31, in get_manager_private_ip
>     return instance['NetworkInterfaces'][0]['PrivateIpAddress']
> IndexError: list index out of range
> 
> Process finished with exit code 1
> 

It seems service role is not created successfully. I'm getting this on ElasticBeanstack application Health check:

> Unable to assume role "arn:aws:iam::888332950069:role/arn:aws:iam::888332950069:role/beiwetest-elasticbeanstalk-service-role". Verify that the role exists and is configured correctly.
> ELB health is failing or not available for all instances.

Not sure what I'm doing wrong.

**Comment by benazir0** [comment]
@writezhe after cleaning up I managed to create manger and worker, but it's failing to deploy. I deleted the the default VPC and created a new default VPC, still it's not deploying. The **beiwetest-elasticbeanstalk-service-role** issue has not been resolved yet. It still says **unable to assume role**. Is this the reason why the backend app is not deploying properly? I am having the same issue that I mentioned here #41

**Comment by benazir0** [comment]
My git's current HEAD is at 6a7200d974b8a75e59c3c2c1b4ec1d7a075cf8aa which was committed about 10 hours ago. I used this command to check `$ git rev-parse HEAD`

**Comment by benazir0** [comment]
Is it possible to tell what codes were changed/added to amend the bug so that I can check whether I'm actually running the correct version of the code base or not? I have pulled all the changes to the development branch, but the arn name is still incorrect.

**Comment by benazir0** [comment]
You can close this issue. It's not happening on the current version.
