### ISSUE TITLE
Deploy a Docker container to the server and run it at least once for a schedule

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-backend#44]
I'm trying to setup the data analysis pipeline. The third paragraph on [this instruction ](https://github.com/onnela-lab/beiwe-backend/wiki/Data-Analysis-Pipeline-setup-and-update-instructions#running-the-data-pipeline-code-locally) says I need to deploy a Docker container to the server and run it at least once for a schedule, but I couldn't find the documentation on how to run a particular job (like monthly.py).

> Currently, you need to deploy a Docker container to the server and run it at least once for a schedule before you can run your code locally for that schedule. This is because to read Beiwe data, the Pipeline code needs to access credentials stored in AWS Parameter Store, and the scheduler running on the Beiwe server is what puts those credentials into AWS Parameter Store in the first place. Therefore, if you haven't yet run a particular job (like monthly.py), there won't yet be any credentials in the Parameter Store for that job, and your local code won't be able to read data from Beiwe.

Therefore, I'm getting error on running the data pipeline code locally because it cannot find the aws parameters on the aws parameter store. Please help.

**Comment by zagorsky** [comment]
The instructions for how to deploy a Docker container are here:
https://github.com/onnela-lab/beiwe-backend/wiki/Data-Analysis-Pipeline-setup-and-update-instructions#creating-and-deploying-docker-containers-to-run-the-data-pipeline-code-on-the-server
