### ISSUE TITLE
ValueError: '(path)/beiwe-backend/cluster_management/pushed_files/rabbitmq_configuration.txt' is not a valid local path or glob

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#46]
Hi all,

I'm trying to setup the escalable server but I got this error when I executed 
`python launch_script.py -create-manager`. I'm running and installing everything from my Linux subsystem in windows 10.

This is the full output:

> Enter the name of the Elastic Beanstalk Environment you want to run this operation on:
> beiwe-env
> INFO cluster-management: creating manager server for beiwe-env...
> ERROR cluster-management: Could not find any instances matching the name 'beiwe-env data processing manager'
> WARNING cluster-management: No manager found.
> INFO cluster-management: Using AMI 'ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20181012'
> INFO cluster-management: Waiting for server i-0bbd45ab0e09cf3b2 to show up...
> INFO cluster-management: Waiting until server i-0bbd45ab0e09cf3b2 is up and running (this may take a minute) ...
> [34.243.251.252] run: # waiting for ssh to be connectable...
> [34.243.251.252] run: echo >> /home/ubuntu/server_setup.log
> [34.243.251.252] sudo: chmod 666 /home/ubuntu/server_setup.log
> [34.243.251.252] put: /home/myuser/beiwe-backend/beiwe-backend/cluster_management/pushed_files/bash_profile.sh -> /home/ubuntu/.profile
> [34.243.251.252] put: /home/myuser/beiwe-backend/beiwe-backend/cluster_management/pushed_files/.inputrc -> /home/ubuntu/.inputrc
> [34.243.251.252] put: /home/myuser/beiwe-backend/beiwe-backend/cluster_management/pushed_files/known_hosts -> /home/ubuntu/.ssh/known_hosts
> [34.243.251.252] sudo: apt-get -y update >> /home/ubuntu/server_setup.log
> [34.243.251.252] sudo: apt-get -y install ack-grep build-essential htop libbz2-dev libreadline-gplv2-dev libsqlite3-dev libssl-dev mailutils moreutils nload sendmail silversearcher-ag python python-pip rabbitmq-server >> /home/ubuntu/server_setup.log
> [34.243.251.252] out: E: Unable to locate package ack-grep
> [34.243.251.252] out: E: Package 'build-essential' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package htop
> [34.243.251.252] out: E: Package 'libbz2-dev' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package libreadline-gplv2-dev
> [34.243.251.252] out: E: Package 'libsqlite3-dev' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package mailutils
> [34.243.251.252] out: E: Package 'moreutils' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package nload
> [34.243.251.252] out: E: Package 'sendmail' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package silversearcher-ag
> [34.243.251.252] out: E: Package 'python' has no installation candidate
> [34.243.251.252] out: E: Unable to locate package python-pip
> [34.243.251.252] out:
> 
> 
> Fatal error: sudo() received nonzero return code 100 while executing!
> 
> Requested: apt-get -y install ack-grep build-essential htop libbz2-dev libreadline-gplv2-dev libsqlite3-dev libssl-dev mailutils moreutils nload sendmail silversearcher-ag python python-pip rabbitmq-server >> /home/ubuntu/server_setup.log
> Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get -y install ack-grep build-essential htop libbz2-dev libreadline-gplv2-dev libsqlite3-dev libssl-dev mailutils moreutils nload sendmail silversearcher-ag python python-pip rabbitmq-server >> /home/ubuntu/server_setup.log"
> 
> Aborting.
> WARNING cluster-management: WARNING: encountered problems when trying to run apt installs.
> Usually this means the server is running a software upgrade in the background.
> Will try 10 times, waiting 5 seconds each time.
> [34.243.251.252] sudo: apt-get -y update >> /home/ubuntu/server_setup.log
> [34.243.251.252] sudo: apt-get -y install ack-grep build-essential htop libbz2-dev libreadline-gplv2-dev libsqlite3-dev libssl-dev mailutils moreutils nload sendmail silversearcher-ag python python-pip rabbitmq-server >> /home/ubuntu/server_setup.log
> [34.243.251.252] out:
> [34.243.251.252] out: Extracting templates from packages: 24%
> [34.243.251.252] out: Extracting templates from packages: 48%
> [34.243.251.252] out: Extracting templates from packages: 73%
> [34.243.251.252] out: Extracting templates from packages: 97%
> [34.243.251.252] out: Extracting templates from packages: 100%
> [34.243.251.252] out:
> 
> Traceback (most recent call last):
>   File "launch_script.py", line 576, in <module>
>     do_create_manager()
>   File "launch_script.py", line 409, in do_create_manager
>     setup_rabbitmq()
>   File "launch_script.py", line 183, in setup_rabbitmq
>     put(LOCAL_RABBIT_MQ_CONFIG_FILE_PATH, REMOTE_RABBIT_MQ_CONFIG_FILE_PATH)
>   File "/home/myuser/.local/lib/python2.7/site-packages/fabric/network.py", line 687, in host_prompting_wrapper
>     return func(*args, **kwargs)
>   File "/home/myuser/.local/lib/python2.7/site-packages/fabric/operations.py", line 381, in put
>     raise ValueError(err)
> ValueError: '/home/myuser/beiwe-backend/beiwe-backend/cluster_management/pushed_files/rabbitmq_configuration.txt' is not a valid local path or glob.

Do you know what's the reason?
Should I get the txt file elsewhere? Or is it missing in the latest commits?
Or is the path incorrect?
I didn't encounter this problem some commits ago.

**Comment by biblicabeebli** [comment]
Hm, this code was recently introduced but worked fine on a whole stack
spinup. I'll try to take a better look at a little later, but in the
meantime try this.

Ensure you are up to date with master.
Terminate any worker and manager servers you have.
Deploy a new manager.
Then deploy a new worker.

**Comment by biblicabeebli** [comment]
Oh, woops, I forgot to add the rabbitmq configuration file to the repo.  I
will get that file added asap.

**Comment by usanchez** [comment]
Hi Eli,

Thanks for answering so fast. I've done this with a fresh clone (9 hours
ago) and have terminated the manager and workers several times.

If the rabbitmq_credentials.txt file is supposed to be in the repo I didn't
obtain it by cloning it and no process has created it neither. I followed
the beiwe-backend wiki tutorial for the deployment.

Thank you very much!

**Comment by biblicabeebli** [comment]
Its actually the global rabbitmq config.  Its pretty simple, it opens just
sets rabbitmq to listen on the correct ports.

**Comment by usanchez** [comment]
So, after you upload the txt file, I just need to rerun the create-manager and will work just fine?

Thank you very much!

**Comment by biblicabeebli** [comment]
We just updated master with what should be a valid rabbitmq configuration
file.

Try deploying your manager and worker servers now.  Please respond on this
thread with whether this has solved the issue.

If any further issues come up feel free to, continue on this thread, I'm
watching it.

**Comment by usanchez** [comment]
Eli, manager up and running with no error! Thank you for your work!

**Comment by biblicabeebli** [comment]
If possible, could you check the celery logs on a worker server and paste
them here?  The logs are in /var/logs/celery, there is an error log and a
regular log.  Celery is the framework that processes tasks, I want to
confirm that it can connect to rabbitmq on the manager server.  The logs
will be pretty short if everything is working, and very obviously long if
something is wrong.

**Comment by biblicabeebli** [comment]
this requires sshing onto the server.

**Comment by usanchez** [comment]
Sorry. I didn't see this last messages. Let me check it.
