### ISSUE TITLE
Error in python launch_script.py -create-manager, permissions?

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#47]
When I run the `python launch_script.py -create-manager` command, I saw this in the verbose. Is this something to worry about? Should I look to correct anything?

> [34.246.198.144] out: Splitting up /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease into data and signature failedE: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
> [34.246.198.144] out:
> 
> 
> Fatal error: sudo() received nonzero return code 100 while executing!
> 
> Requested: apt-get -y update >> /home/ubuntu/server_setup.log
> Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get -y update >> /home/ubuntu/server_setup.log"
> 
> Aborting.
> WARNING cluster-management: WARNING: encountered problems when trying to run apt installs.
> Usually this means the server is running a software upgrade in the background.
> Will try 10 times, waiting 5 seconds each time.

Is it related to issue #40 ?

**Comment by biblicabeebli** [comment]
As long as he apt installs eventually finish and install correctly this is
expected behavior.  I don't know why, best guess is system updates are
still executing, but sometimes the apt installs fail with bizarre error
messages, so we wrap it in a retry loop.

**Comment by biblicabeebli** [comment]
And no, not related to #40.
