### ISSUE TITLE
Research platform download data downloads empty .zip folder

### ISSUE THREAD

**Issue by cmbosma** [onnela-lab/beiwe-backend#54]
I have collected pilot data using the Beiwe app. When I attempt to download data on the Beiwe research platform, it generates an empty .zip file. I have checked my S3 bucket and the data is there. Please let me know if you require additional information to troubleshoot this issue.

**Comment by mariasimoneau** [comment]
Some ideas..

1.  Did you select your study, PIDs, sensors and enter the date range?  Are you entering the right dates when data was actually being collected?  (https://github.com/onnela-lab/beiwe/wiki/Beiwe-Research-Administration-Website#download-data-tab)

2. Did you configure your study as a production study?  Only "test" study settings will give you the raw data.

> From the setup screen:
> 
> This study involves:
> 
> Test data: researchers will be able to download raw data and processed data output from the Data Analysis Pipeline. Use this setting for testing and debugging.
> 
> Production data: researchers will only be able to download processed data output from the Data Analysis Pipeline. This setting is higher security. Use this setting if your study will involve actual patient data.

Some possible work arounds:
-SSH into the server and change the studies from Production to Test on the database. 
-I wonder if you use the mano script for the downloading data if that will work?  (https://github.com/onnela-lab/beiwe/wiki/Using-mano)
-If you want to keep the study as "production" then you'll need to set up the data analysis pipeline and use the available methods for analyzing the data.  This is a work in progress.   (https://github.com/onnela-lab/beiwe-backend/wiki/Data-Analysis-Pipeline-setup-and-update-instructions).

3. I'm not certain and empty zip file is the failure mode but sometimes the 'data chunking' capability isn't working properly.  This effectively puts the data collected from the phones into the .csv files that are ultimately downloaded.   I believe there are other issues addressing this?

**Comment by cmbosma** [comment]
I configured my study as a production study, as I am collecting patient data.

I set up my environment for running the Beiwe analysis code locally and I began setting up the data analysis pipeline, until I noticed it was in development when I inspected the runner.sh shell code. 

Is there a timeline for when the data analysis pipeline development will be completed?

In the meantime, I will try the mano script. 

Thank you for this helpful information.

**Comment by cmbosma** [comment]
I configured my study as a production study, as I am collecting patient data.

I set up my environment for running the Beiwe analysis code locally and I began setting up the data analysis pipeline, until I noticed it was in development when I inspected the runner.sh shell code. 

Is there a timeline for when the data analysis pipeline development will be completed?

In the meantime, I will try the mano script. 

Thank you for this helpful information.

**Comment by cmbosma** [comment]
Hello @mariasimoneau , 

I tried using the Mano library and ran into an issue with the download() function accessing the wrong URL, which I have made an issue on their github repo. 

I also looked into changing my study settings from "Production" to "Test" and noticed those options are not visible to me when I create a new study on the setup page. When combing through beiwe-backend repo, I noticed these options are available in a .html template file; however, I cannot find how to change this setting for my studies when I SSH into my server. Could you point me in the right direction for making this change?

I also fixed the data chunking bug in my server, since this was fixed after I set it up, but that did not make a difference in terms of downloading data.
