### ISSUE TITLE
Unable to login using default credentials after deployment

### ISSUE THREAD

**Issue by abhineethreddyk** [onnela-lab/beiwe-backend#55]
Hello, 
I'm trying to deploy and run Beiwe cluster. Following the instructions in the wiki, I was able to deploy and access login page. However, unable to login using default credentials admin-admin. Here are a few additional details:
* Using Ubuntu 18.04.2
* Python 2.7.15rc1
* boto3 1.9.134
* botocore 1.12.136
* fabric 1.14.0
* coloredlogs 7.3
* AWS region us-east-2
* EB CLI 3.15.0 (Python 2.7.1)
* In _.elasticbeanstalk/config.yml_:
    * chanted _default_platform_ to '64bit Amazon Linux 2018.03 v2.8.2 running Python 2.7'  from '64bit Amazon Linux 2018.03 v2.7.0 running Python 2.7' (was running into v2.7.0 doesn't exist error) 
    * changed _application_name_ to 'beiwe-application' from 'Beiwe Cluster' (Github code had 'Beiwe Cluster')
* Used _sudo_ for _python launch_script.py -create-manager_ (was running into 'permission denied to access pem file' error)

I followed all the steps exactly as given in the deployment instructions. Please let me know if any additional details about my workstation, packages, or anything else would help.
Thank you

**Comment by biblicabeebli** [comment]
Woops, looks like documentation was wrong about those defaults.

username is default_admin
default password is abc123.

I've updated the documentation on the wiki.

Please let me know if that is the core of the issue so that I can close the ticket.

**Comment by abhineethreddyk** [comment]
Yes, this is the only issue. I'm able to login using the given credentials. Thank you.
