### ISSUE TITLE
Have cluster management reference ~/.aws/credentials and AWS env variables

### ISSUE THREAD

**Issue by erinn** [onnela-lab/beiwe-backend#58]
Have the cluster management section reference those variables and or configuration files exactly in line with how boto handles them instead of just having them hard coded into a file. 

There is also a hidden issue with the hard coding approach which is that if a user does have a ~/.aws/credentials file that is valid (but not for the VPC you are currently working on), when following the deployment instructions and you get to https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#set-up-the-aws-elastic-beanstalk-command-line-interface-eb-cli all of the sudden the eb CLI starts using the credentials from either the env variables or from the configuration file.

This can cause some confusion. It would probably be best if the launch_script.py used env variables and the credentials file in the normal order of precedence the same as most other aws tools do, if not for convenience sakes, then to minimize confusion like the above.

**Comment by biblicabeebli** [comment]
Good to know, had not encountered that, this is a good idea.

**Comment by biblicabeebli** [comment]
(somehow posted responses on the wrong threads...)

Nothing inherently against this, it would certainly be helpful
I'm not sure how to maintain this.

Details:

    AWS cred files can have multiple user options, how would we handle that?
    Don't have a real understanding of how AWSCLI and AWSEBCLI treat this file or expect this file.
    Might it be possible to use AWSCLI and AWSEBCLI to get the credentials? that would be great because we would just hook into that.
    I think a better solution would be to simplify all the settings file. They were developed incrementally, they need to be unified.
