### ISSUE TITLE
Have a delete option for the cluster manager

### ISSUE THREAD

**Issue by erinn** [onnela-lab/beiwe-backend#59]
Having run into #56 previously, the script had created the RDS instance as well as a couple of security groups, but errored out on creating the S3 bucket. This essentially broke the cluster build out in the middle which is fine, but trying to subsequently run the create-environment failed because the RDS instance and security groups were already in place. 

It would be great to have a delete cluster option, or a reset to defaults, or something along those lines so that when the build out inevitably fails in the middle due to some weird glitch, it isn't a hunting game to find out what has been created in the VPC and manually deleting those in order to step through the build out again.

Would also just be really handy for folks who want to prototype (though I am aware you could just create a new VPC).

**Comment by biblicabeebli** [comment]
Nothing inherently against this, it would certainly be helpful, but it is and I'm not sure how to maintain keeping it up to date.

**Comment by biblicabeebli** [comment]
This would be an excellent relatively small development task that at-most requires a bit of sysadmin experience and requires no understanding of the server code.  Marking as help wanted.

**Comment by biblicabeebli** [comment]
This has been implemented and is now on master.
