### ISSUE TITLE
when adding/deleting surveys, surveys are not deleting

### ISSUE THREAD

**Issue by mariasimoneau** [onnela-lab/beiwe-backend#6]
A collaborator has 4 surveys. 1, 2, 3 are to deliver respectively on enrollment (day 1), Day 2,  and  Day 3.  The 4th one has 35 questions and is randomized to deliver daily starting on day 4.   On day four he goes in and deletes surveys 2&3 (1 was just on enrollment) and edits the 4th survey to add day 1,2&3 so it is scheduled for the full week now.    We're testing two phones.  Surveys 2 & 3 come again the following week as previously scheduled.  On one participant, they’re getting the deleted survey twice on the previously scheduled day. 

I have a hunch that randomized option on the 4th survey is affecting things somehow.  And I’ve seen a deleted survey show up days after deleting them.  (I hadn’t been testing this, so I hadn’t noted when the survey was scheduled but then one randomly showed up on Saturday after I had deleted it on Tuesday.)

This is reported from a collaborator who is testing out their pilot which has not yet begun.  they've been testing on fellow employees so i'm sending you the (fake) data.

**Comment by zagorsky** [comment]
Fixed in Beiwe Android app version 2.1.4.
