### ISSUE TITLE
Data pipeline wiki clarifications

### ISSUE THREAD

**Issue by erinn** [onnela-lab/beiwe-backend#62]
This paragraph was pretty vexing while trying to figure out how to set up the data pipeline:

> Currently, you need to deploy a Docker container to the server and run it at least once for a schedule before you can run your code locally for that schedule. This is because to read Beiwe data, the Pipeline code needs to access credentials stored in AWS Parameter Store, and the scheduler running on the Beiwe server is what puts those credentials into AWS Parameter Store in the first place. Therefore, if you haven't yet run a particular job (like monthly.py), there won't yet be any credentials in the Parameter Store for that job, and your local code won't be able to read data from Beiwe.

It then goes on to describe a local setup, then the pipe line setup, but nowhere is it clear HOW to actually run the initial job. I just guessed by poking around the AWS console and hitting batch, then firing off a manual job from there, which did populate SSM with the right parameters, though I am still not sure that was the way.

If the pipeline has to be built in order for the local pipeline work to happen, the doc should probably be reorganized with the pipeline build at the top running through the steps, and indication about how to fire off the first job, then explain the local setup, removing the bit about developing locally first before building the pipeline.

**Comment by biblicabeebli** [comment]
Thanks for the input, there is active development that has been stalled for
a bit on the pipeline, so I will see what I can do about updating and
reorganizing the docs.

**Comment by biblicabeebli** [comment]
The underlying development work on the pipeline got interrupted by python 3 work, and extensive delays on the accelerometer pipeline data stream due to R problems.  Will be posting content I have in emails with the original developer on a new issue.

**Comment by biblicabeebli** [comment]
Pipeline is being deprecated, closing.
