### ISSUE TITLE
Unable to update code for single-server deployment

### ISSUE THREAD

**Issue by cmbosma** [onnela-lab/beiwe-backend#65]
After SSH-ing into my server and running `$ git pull`, I get the following error:

> Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.

>ERROR: We're doing an SSH key audit.
Reason: unverified automatically (private key found in a public repository)
Please visit https://github.com/onnela-lab/beiwe-backend/settings/keys/16124728
to approve this key so we know it's safe.
Fingerprint: d1:96:8c:92:66:4f:ef:f1:5b:12:ea:ee:ac:aa:90:e4

>fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
and the repository exists.

The URL "https://github.com/onnela-lab/beiwe-backend/settings/keys/16124728" no longer exists and I did not find documentation on how to get SSH keys approved.

**Comment by biblicabeebli** [comment]
Hello, sorry about the delayed response.

I'm trying to resolve this but I do not currently have the administrator
rights to check that url either.
I believe what is occurring is that an automated github repository scan has
caused the key you use to be disabled.

Are you running the AMI release of Beiwe?  The git key provided there could
be out of date / no longer necessary.

Try changing the git config to point at the repo using https instead of
using ssh with a key.
This is perfectly safe and secure, I believe we made this change due to an
issue like what I described above occurred several months ago.
url is https://github.com/onnela-lab/beiwe-backend.git

**Comment by cmbosma** [comment]
Hello,

Thank you for this information. I will try changing my git config to point
at the repo.

How can I confirm whether I am running the AMI release of Beiwe?

Best,
Colin

**Comment by biblicabeebli** [comment]
The AMI is the Amazon Machine Image.  If you are running a single server deployment (not an elastic beanstalk server cluster) then you are on the AMI.

Did changing the git endpoint resolve your issues?  If so I would like to close this issue.

**Comment by cmbosma** [comment]
Hello Eli,

Thank you for the clarification. Yes, I am on the AMI.

I will be able to try changing the git endpoint this evening. I will go
ahead and close the issue if it resolves the issue.

Thank you!

Best,
Colin

**Comment by biblicabeebli** [comment]
I would like to close this issue, can you confirm whether the git config fix resolved your problems?

Please be aware there is an immanent python 3 release for the entire codebase.  The AMI is not configured in a way that will allow for conversion, so you will want to swap to the python2-legacy branch.

python2-legacy is the current state of production, I just created it.  You will have to manually run python manage.py migrate to update the database schema.

**Comment by cmbosma** [comment]
Hello Eli,

Thank you for your help with this issue. I resolved it as I was able to
update my old deployment of Beiwe.

When should I expect the python 3 release? And when that happens, can I
update the code for the python 3 release as outlined on the deployment
instructions page of the wiki?

Best,
Colin

**Comment by biblicabeebli** [comment]
Deployment of new clusters will be identical, there will be instructions of how to do a cluster conversion, but converting an AMI instance is not really a thing we have thought about.

It shouldn't be that hard for a sysadmin familiar with python.  Set apache to use python 3, pull the new code, install the new python 3 library requirements, run database migrations, update bash aliases and cron jobs to use python 3.  There are also some system dependencies that have changed, if you look in cluster_management/deployment_helpers/constants.py there are apt install details.  It is for 18.04 though so could be different, and doesn't include the apache details.

I'm not going to have time to set up a new AMI any time soon, it just is not a high priority for the project right now.  I would appreciate any help on getting a newer AMI to happen.  If you spend any time putting together a new server (ubuntu 18.04 preferably) and sending your notes or a bash script our way that would be... awesome?  Or, if you are truly adventurous, a conversion script for an already configured python 2 ubuntu 16.04 server.  (... the existing AMI is 16.04, right?)
