### ISSUE TITLE
Update Your Amazon RDS SSL/TLS Certificates by October 31, 2019

### ISSUE THREAD

**Issue by benazir46** [onnela-lab/beiwe-backend#71]
We received this email below from amazon. Do we need to update anything since we are using PostgreSQL not Aurora? On the second step provided in the link https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html says, we need to update our client application with the new certificate. Could you elaborate how to do that?
_________________________________________________________________________
Hello,

Please act before October 31, 2019 to address an upcoming interruption of your applications using RDS and Aurora database instances.

To protect your communications with RDS database instances, a Certificate Authority (CA) generates time-bound certificates that are checked by your database client software to authenticate any RDS database instance(s) before exchanging information. Following industry best practices, AWS renews the CA and creates new certificates on a routine basis to ensure RDS customer connections are properly protected for years to come. The current CA expires on March 5, 2020, requiring updates to existing RDS database instances with certificates referencing the current CA.

You are receiving this message because you have an Amazon RDS database instance(s) in the AP-NORTHEAST-1, AP-NORTHEAST-2, AP-SOUTHEAST-1, AP-SOUTHEAST-2 Region(s). If your applications connect to those instances using the Secure Sockets Layer (SSL) or Transport Layer Security (TLS) protocol please follow the detailed instructions in the link below to complete your update(s). If not completed, your applications will fail to connect to your DB instances using SSL/TLS after March 5, 2020.

We encourage you to test these steps within a development or staging environment before implementing them in your production environments. Beginning today, you can start testing and updating your existing RDS database instances. For detailed instructions, please visit: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

Any new RDS instances created after November 1, 2019 will default to using the new certificates. If you wish to temporarily modify new instances manually to use the old (rds-ca-2015) certificates, you can do so using the AWS console or the AWS CLI. Any instances created prior to November 1, 2019 will have the rds-ca-2015 certificates until you update them to the rds-ca-2019 version.

If you have questions or issues, please contact AWS Support at: https://aws.amazon.com/support

Sincerely,
Amazon Web Services
_____________________________________________________________________

**Comment by biblicabeebli** [comment]
This is a general system administration question.
The message is quite specific in that it only refers to Aurora databases.
Beiwe does not use Aurora databases.

**Comment by biblicabeebli** [comment]
Ah, apologies, you were asking about whether there was a beiwe-side
corresponding update.  simple answer is no, but this is now on my radar and
if there is a situation I will resolve it asap and you can reach out to me.

**Comment by benazir46** [comment]
No worries. We are updating the certificate of the rds instance from ds-ca-2015 to rds-ca-2019 as suggested. If the applications do not use Secure Socket Layer (SSL) or Transport Layer Security (TLS) to connect to the db instance, it won't have any issue.

**Comment by biblicabeebli** [comment]
Confirmed:
No action is required with the Beiwe servers.  Beiwe makes use of an encrypted database session but does not appear to require any configuration change to support the updated database certificate.

(To those discovering this thread: recommend running an AWS platform upgrade first.)

**Comment by benazir46** [comment]
Awesome! Thanks

**Comment by benazir46** [comment]
Hi Eli, our server is down after the update. Data are not being uploaded and we can't login to the web interface anymore. Here is the Sentry log:

`OperationalError: SSL connection has been closed unexpectedly

(7 additional frame(s) were not displayed)
...
  File "libs/user_authentication.py", line 34, in validate_post_ignore_password
    if not participant_set.exists():
  File "django/db/models/query.py", line 673, in exists
    return self.query.has_results(using=self.db)
  File "django/db/models/sql/query.py", line 517, in has_results
    return compiler.has_results()
  File "django/db/models/sql/compiler.py", line 858, in has_results
    return bool(self.execute_sql(SINGLE))
  File "django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception`

**Comment by benazir46** [comment]
Fixed it. I had to restart the application. it's working fine now.

**Comment by biblicabeebli** [comment]
yeah, for some reason you have to do that when you pull the database out from under beiwe.  Do not know why.
