### ISSUE TITLE
Problem with EB deployment (python3 scalable server)

### ISSUE THREAD

**Issue by er42** [onnela-lab/beiwe-backend#73]
Since it sounds like the Python 3 release is now functional and the old Python 2 code (including the single-server architecture) is nearing the end of its lifespan, I decided to go ahead and try setting up a new scalable deployment using the python3 branch of the beiwe-backend code. 

Things went relatively well until I got to the `eb deploy` stage. There, things hit a snag. The first problem resulted in the error

`Command failed on instance. Return code: 1 Output: (TRUNCATED)..._and_salt("abc123") File "/opt/python/bundle/3/app/libs/security.py", line 82, in generate_hash_and_salt password_hashed = encode_base64(pbkdf2('sha1', password, salt, iterations=ITERATIONS, dklen=32)) TypeError: a bytes-like object is required, not 'str'. container_command 04_migrate in .ebextensions/01.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.`

I was able to find the bug that was causing that failure. Because of the python upgrade, line 18 of `beiwe-backend/database/migrations/0005_add_admin_user.py' needed to be changed from

`password, salt = generate_hash_and_salt("abc123")`
to
`password, salt = generate_hash_and_salt(b'abc123')`

After committing that change and redeploying to EB, I got a different error that has me stumped:

`Command failed on instance. Return code: 1 Output: (TRUNCATED)...jango/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) django.db.utils.ProgrammingError: column database_researcher.is_batch_user does not exist LINE 1: ..., "database_researcher"."access_key_secret_salt", "database_... ^. container_command 04_migrate in .ebextensions/01.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.`

The error clearly has something to do with creating the default_admin user and adding that user to the django database, but I can't figure out exactly why the error is happening or how to fix it. `0023_auto_20191003_1928.py` has several references to `is_batch_user`, so I suspect something in this file might be the culprit, but I don't know enough about django to diagnose exactly what's causing the error. Also, for some reason when I try to check the detailed logs I get an HTTP Error 403: Forbidden error, which doesn't help matters.

Any ideas?

**Comment by biblicabeebli** [comment]
Oh, hey, sweet.  It is the full stack deployment that has not been tested, so this is great!

woops, looks like I missed a detail of the batch task "user" type (Its a fake user that bypasses credentials and has access to all data so that it can download and process data.) and a byte string in a migration.

Python 3 is pretty close to ready, I'm running it on our staging setup, collecting bugs, development only stopped because of an office move.

I.... don't know what those logs access errors are about...

I'll look at this as soon as I have more than cardboard boxes, should be pretty easy.  (I wonder how I failed to track a property usage like this one down, rookie bug.)

**Comment by biblicabeebli** [comment]
Allrighty, I have now tested with a couple different states of the database, including an empty database.  Should run now.  Changes pushed on the python3 branch.

**Comment by er42** [comment]
I just deployed again using the updated code and I didn't get these errors anymore, so it seems to be working now. I'll go ahead with the DNS/SSL configuration next and then confirm whether there seem to be any other issues.

Thanks for fixing this!

**Comment by biblicabeebli** [comment]
Awesome.  I just merged this code into master, I’m working on getting this
onto my production server cluster now.

**Comment by biblicabeebli** [comment]
Woops, delinquent on my github comments.

I have made several fixes that should clear up migration issues on initial deploys.  Comment if you recheck and it has not.

Code has been merged into master.
