### ISSUE TITLE
File uploads being revoked (HTTP code 308)

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#74]
Hi,

I just realised that some users are trying non-stop to upload file but our server is sending a _308_ response all the time. 

I debugged the app with my smartphone but I saw no error when I forced to upload the files. Looking at the android code:

```
try {
                    file = new File(appContext.getFilesDir() + "/" + fileName);
//				Log.d("uploading", "uploading " + file.getName());
                    if (PostRequest.doFileUpload(file, uploadUrl, stopTime) == 200) {
                        TextFileManager.delete(fileName);
                    }
                } catch (IOException e) {
                    Log.w("PostRequest.java", "Failed to upload file " + fileName + ". Raised exception: " + e.getCause());
                }
```

I didn't have any "Failed to upload file message" in the Logcat.

On the server, I'm having these logs:

```
IP address (IP address) - - [29/Nov/2019:11:48:35 +0000] "POST /upload HTTP/1.1" 308 277 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-G960F Build/PPR1.180610.011)"
IP address (IP address) - - [29/Nov/2019:11:48:35 +0000] "POST /upload HTTP/1.1" 308 277 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; MotoG3 Build/MPIS24.107-55-2-17)"
```

I want to get the response to the `/upload` petitions, because I think that in the `Location` header I can find what URL the server is suggesting.

**EDIT**: So I got the response to a /upload petition and it told me this:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a
		href="https://URL.com/upload/">https://URL.com/upload/</a>. If not click the link.
```

Does this mean that the URL of the app should point to `/upload/` instead of `/upload`?

**EDIT 2**: I've been tweaking the app and if I change the `data_upload_url` to `/upload/` (previously just `/upload`) in the Android app, it works, the problem is solved. However, this solution would require to update all apps. Is there anything I can do to find a solution to this problem that only requires to change server code?

**Comment by usanchez** [comment]
I also found in the ssl_error_log the following line:

`AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions : /var/www/cgi-bin/day5notifier`

So maybe, if I solve this issue first, the file upload will work again?

**Comment by er42** [comment]
Hmm, this looks potentially related to an issue we encountered also (https://github.com/onnela-lab/beiwe-backend/commit/c51cd6cb9355e3d0cbb99bb375cc05025223bee0).

**Comment by biblicabeebli** [comment]
**Gr arg this bug.**

**usanchez:** could you please provide that rewrite rule?  (and yes adding it to that config file will make it permanent.)

**er42:** could you try out the rewrite rule and also test its behavior with a reversion of the c51cd6c commit?  (I have been unable to replicate this bug, it now appears to affect multiple deployments.)

**Oh Goodie and now the master branch is Python 3** and I'm dogfooding it on our main production server, and I can't exactly revert back.  (Earlier today I pushed the fixes to the remaining issues that cropped up over the holiday week, it is nearly ready for 3rd party production servers.)  You two should still be on Python 2 (the current production branch) for debugging this.  I have no idea what will happen when/if you upgrade to Python 3.  If we can get a working Python 2 version for reference I will update the legacy python 2 branch to include this fix.  My best guess at this point is that WSGI / the relevant Python werkzeug library (most likely the latter) is causing this issue, but I am generally baffled.  Sorry I've been unable to track this one down, thank you both for tracking this down and contributing.

**Comment by usanchez** [comment]
Yeah, glad to help.

I SSH'd into the environment machine and created a file called `upload_rewrite.conf` in the path `/etc/httpd/conf.d/`, the command to create it:

```
sudo nano /etc/httpd/conf.d/upload_rewrite.conf
```

The contents of the file are the following ones:

```
RewriteEngine  on
RewriteRule    "^/upload"  "/upload/" [PT]
```

Then I gracefully restarted `httpd` (`sudo httpd -k graceful`) and got it working. Got rid of the permanent redirects.

For a permanent temporary fix for this, should we
1. include this new file in the folder `pushed_files` inside the `cluster_management` folder, and,
2. in the file `01.config` include a command to copy the file:

```
  05_upload_permanent_redirect_fix:
    command: mv ./cluster_management/pushed_files/upload_rewrite.conf /etc/httpd/conf.d/upload_rewrite.conf
```

**Comment by biblicabeebli** [comment]
that's one way to do it and honestly that's fine imo.  there is also an existing rewrite rule elsewhere in one of those aws/elastic beanstalk config files (commuting, sorry) with an alternate mechanism of pushing.

As long as this does not break the non-ssl to ssl rewrite rule i'm cool with it.

**Comment by usanchez** [comment]
I have checked the latest ssl logs and I see no errors whatsoever and uploads are getting the 200 code.

**Comment by biblicabeebli** [comment]
Great, the uploads getting 200s is good.
( /¯ °3° )/¯

I don't know that the SSL log would have anything?  The rewrite rule for SSL makes all http requests redirect to the identical https endpoint.  (though I'm not an expert at debugging Apache itself, only the code running behind Apache.  This might be the reason I could not replicate the bug.)

**Comment by biblicabeebli** [comment]
Right, the way to test the https rewrite rule is to go to the website but explicitly typing in the address as 'http' and seeing what happens.  Compare to studies.beiwe.org to confirm behavior.

Do this in an incognito tab / literally a totally fresh browser that has never even once been to your website. This is because we also use HTTPS-Everywhere (I think that is what it is called? there's a lot of "ssl Things" these days.)

**Comment by biblicabeebli** [comment]
Okay, I have been testing this.
This managed (lol...) to uncover a forgotten todo from the python 3 port, so that became the next hassle.  I'm pushing a fix on the master branch, then updating the python 2 legacy branch.  I no longer have a python 2 server active so I will need you to confirm that the ported fix works.

**Comment by er42** [comment]
Hey, sorry for the delay -- it's been a crazy week around here. I am finally getting a chance to troubleshoot this now.

First of all, the system I am using this on is using the new master branch version with Python 3, so unfortunately I won't be much help debugging the Python 2 version.

I first tried just rolling back https://github.com/onnela-lab/beiwe-backend/commit/c51cd6cb9355e3d0cbb99bb375cc05025223bee0 and that did not go well. No data were uploaded on android, and Sentry got swamped with error reports for 10k upload events from one device within half a day. (oops; should have been keeping an eye on that.) The specific error logged on Sentry was `AssertionError: ('elif "file" in request.values', <class 'str'>)`. I reverted the revert and the errors stopped.

After that, I tried applying the `upload_rewrite.conf` fix described above. So far, I still don't seem to be getting any Android data, but I'm not sure if I applied the fix correctly. Is it supposed to be done on the machine accessed via `eb ssh` (i.e., the instance that isn't the data processing server/manager)? That's the machine I added `upload_rewrite.conf` to. 

If that's the correct instance, then could the continued android upload failures be related to the forthcoming python 3 fix mentioned in the last post? Or maybe the android device I'm testing on has something cached wrong that will take some time to reset itself?

Anything else I should try testing?

**Comment by biblicabeebli** [comment]
I have a working python 3 situation, , I got delayed repeatedly after
testing it last night and have not pushed.  sorry.

The redirect does nothing in python 3, the solution there is to delete the
"upload/" endpoint.  I debugged and fixed that next one, the assertion is a
leftover from debugging, it did its job and caught a condition that would
have been otherwise obnoxious to work out.  I'll push asap.

I have no idea what the tornado of events that have resulted in these
different-but-similar bugs is.  I am fairly confident that adding the
"/upload/" endpoint broke only python 3 (I never experienced he issue on my
production server until I upgraded my stack) and that something else is
going on with python 2. However we seem to have a report here of the exact
upload error on a python 2 stack.

usanchez: are you running python 2 or python 3?

**Comment by usanchez** [comment]
I tested the HTTPS thing and seems to be working well on an incognito window.

I'm using python 2. I did the steps described in my previous post and I got it working. Haven't tested on python 3 yet. I'll try soon but cannot give a date for it yet.

Thanks for all your effort. I'll keep you updated.

**Comment by biblicabeebli** [comment]
Okay, FYI you can't go back to the python 2 code if you upgrade.

**Comment by usanchez** [comment]
Tomorrow I'll start with the update to `python3`, but I have a doubt about the steps described in the wiki [Upgrading from Python 2 to 3](https://github.com/onnela-lab/beiwe-backend/wiki/Upgrading-from-Python-2-to-3). In step 7, it is stated the following:

> Use git to check out onto the production branch

Should we still use the `production` branch to update to `python3`? As you have stated in this thread, the `master` branch is already `python3`, so I thought that we could checkout to `master` in this step, and, additionally, `production` is **77** commits behind `master`. So I guess that the wiki just needs to have that part updated.

Thanks!

**Comment by usanchez** [comment]
As an update after upgrading the platform to Python3: files are being uploaded correctly without the redirect error and without needing to add any rewrite rule or a second route for the upload.
