### ISSUE TITLE
rabbit_mq_password.txt file not being created with the correct name

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#79]
Hi,

In the process of upgrading the code to Python3 and launching the new manager server, I've seen that the `rabbit` password is being stored in a file called `cluster_managementrabbit_mq_password.txt`. Is that supposed to be okay? Or is the filepath incorrectly stated here?:

```
# Well... this should have been CLUSTER_MANAGEMENT_FOLDER + 'rabbit_mq_password.txt', but this has
# already been deployed for months.  TODO: insert some code here to safely fix this.
RABBIT_MQ_PASSWORD_FILE = CLUSTER_MANAGEMENT_FOLDER + 'rabbit_mq_password.txt'
```

The first time that I had to deal with the deployment, I changed that piece of code to

```
RABBIT_MQ_PASSWORD_FILE = path_join(CLUSTER_MANAGEMENT_FOLDER, 'rabbit_mq_password.txt')
```

And I think that it worked, but I don't know right know if I'll be messing up with anything if I "fix" this filepath constant.

**Comment by biblicabeebli** [comment]
WOOPS.
I .... I definitely put in time to fix this.  I guess that work got lost?
Yup I'm seeing it on my own local config too.  Oh goodie.

Unfortunately this will require terminating and spinning up new data processing servers this file is weird, I don't know if it is even per-deployment.  Not my finest hour.

On the plus side I'm working on a bug fix for data processing that will hopefully result in a couple advantages, so the update will be worth it.

(There will not be a Python 2 fix for this.)

Thanks for the report.

**Comment by usanchez** [comment]
Okay, thanks Eli! Don't worry we all have those moments :)

I have no data processing servers right now, just the manager server. Or does it count as a processing server after the changes?

Good to hear about the new changes bringing extra advantages! Thanks for all your effort. I'll try to keep you all updated on issues, just so it may be of any help.

**Comment by biblicabeebli** [comment]
I ended up with a different fix, it is on development right now.  My fix makes the variable deployment-specific.  You will need to deploy new managers and workers for it, but there is another change that is present that will require some manual operations anyway.  I'll push it all to master as soon as I finish writing up the directions on the wiki.

**Comment by usanchez** [comment]
Thanks Eli! I'll test it as soon as you have it on master and give you feedback.

Thanks for all your effort!
