### ISSUE TITLE
'eb deploy' - ERROR: InvalidParameterValueError - No Application Version named 'app-4911-200101_232529' found.

### ISSUE THREAD

**Issue by jakehemmerle** [onnela-lab/beiwe-backend#82]
I was able to solve this by using 'eb deploy --interactive' and specifying stuff manually. Then the upload to S3 worked just fine. Would this also be useful to add to the wiki?

**Comment by biblicabeebli** [comment]
I'm not sure what could cause this?  Unless maybe you are not using git so it doesn't know the files that are part of the repo?

the way the commandline tool works is it zips the current state of _committed_ code [fyi there is a very useful --staged parameter] and sticks it on s3, then tells the server to go download it.  So... it didn't upload?  ¯\_(ツ)_/¯

**Comment by biblicabeebli** [comment]
lol it stripped the backslash on my shrug....

**Comment by biblicabeebli** [comment]
@jakehemmerle can you confirm or deny my question about whether you are using git?

**Comment by jakehemmerle** [comment]
@biblicabeebli yes I have been using git, sorry for not replying :)

**Comment by biblicabeebli** [comment]
Hm.  I have no idea what could have happened, I've been using the eb command line tool (along with all my coworkers) for ... years.  I've never seen or hard of this issue.

Let's keep the thread open, please let me know if you work out what caused this.  If it remains a mystery I will update the wiki with a warning.

**Comment by jakehemmerle** [comment]
Will do.

**Comment by biblicabeebli** [comment]
I would like to close this issue as it isn't really a Beiwe issue, and I'm not really sure how to address an issue with the eb tool that I have never heard of and only had one report of.

**Comment by jakehemmerle** [comment]
I have not been able to reproduce the issue.

**Comment by litingzhou1** [comment]
I met the same problem and don't know how to do

**Comment by biblicabeebli** [comment]
if you are able to reproduce the problem and post the full terminal output feel free to post the issue.

**Comment by biblicabeebli** [comment]
if you are able to reproduce the problem and post the full terminal output feel free to post the issue.

**Comment by justinpincar** [comment]
For future Googlers: this error message is also caused by an incorrect `application_name` in `.elasticbeanstalk/config.yml`

**Comment by biblicabeebli** [comment]
Thank you for posting, I appreciate the SEO!

(Would love to hear from you personally, always looking for active users and feedback, and contributors where possible. My email is in a pinned issue.)
