### ISSUE TITLE
Track changes to study device settings and allow researchers to see the study device settings a particular participant has.

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#85]
Track changes to study device settings and allow researchers to see the study device settings a particular participant has.

Study device settings are currently not tracked, so changes in them cause confusion.
If we track device settings changes like we do survey changes then we can associate participants with their state.

To present the data maybe shadow the presentation of study device settings but read-only.

**Comment by usanchez** [comment]
Same thing I mentioned in https://github.com/onnela-lab/beiwe-backend/issues/86.

This would imply to start tracking the Device settings of each participant, right? Right now the only Device settings info comes from the Study, that is unique for all devices in the study, and does not take into account if two participants of the same study have different settings. Am I right?

**Comment by biblicabeebli** [comment]
I _think_ you have interpreted me correctly?

**Comment by biblicabeebli** [comment]
Just clarifying as I'm reviewing open issues:
The current structure is that settings exist in one spot and are associated with a study.  A participant receives settings at registration and then never checks in again, so their settings are a snapshot of that moment in time.

Tracking changes means that researchers can check the settings for a specific user, it also would be a first step towards allowing per-participant device settings.

**Comment by usanchez** [comment]
I think that to do so, It would be cool to implement DeviceSettingsArchive (to copy the system with AbstractSurvey - Survey - SurveyArchive), and then ParticipantSurveyArchive would be a table that relates participant_id to device_settings_archive_id, linking the settings of a participant's device to a version of those settings.

However, do we also want to track the settings' history of one participant? If a participant has to reinstall the app, it would receive new settings...

**Comment by biblicabeebli** [comment]
good feedback, don't have answers.  Will ponder.

**Comment by biblicabeebli** [comment]
I'm deprecating this issue in favor of syncing live settings from the backend server. the need for a historical record of device settings was overestimated.
