### ISSUE TITLE
track data download events, sizes, times, and the actual queries

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#86]
This kind of administrative knowledge, even if it is limited to sysadmins, is an important administrative detail to provide, even if it is never surfaced in the UI and only visible to sysadmins.

**Comment by usanchez** [comment]
Eli, this is something I was researching not too long ago, not only to track (audit) data download but also to track anything else. I haven't looked more in-depth into it, but there are several Django apps that could make this job easier (from object to model auditing): https://djangopackages.org/grids/g/model-audit/ 

Is this something that could be useful?

**Comment by biblicabeebli** [comment]
that app may be useful, I'll have to research it some, but I don't think that the data we should track is particularly complex.  Don't want to add complexity if I don't have to.

The data we currently track is data upload and changes to surveys.

I guess we could track data processing too, anything else?

**Comment by biblicabeebli** [comment]
implemented.
