### ISSUE TITLE
rabbitmq has known issues, replace queue backend to resolve them

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#93]
Celery/Celery tasks are sometimes.... unsuccessful in connecting, the system emits an ampq connection error.  The reason is unclear, but it appears to be a rabbitmq issue.

If this issue remains swap the system over to use reddis for the celery task queue backend.

**Comment by biblicabeebli** [comment]
Newer versions of celery have a django backend!  that would reduce complexity of deploying and of security group management potentially substantially!

needs research.

**Comment by biblicabeebli** [comment]
Misread documentation about this, django cannot be used for the queue, our best option is to replace with redis and hope it isn't as problematic.

**Comment by biblicabeebli** [comment]
alternative: try out Huey, a less complex task dispatch python library.
[https://huey.readthedocs.io/en/latest/](https://huey.readthedocs.io/en/latest/)

**Comment by biblicabeebli** [comment]
Okay, last straw, we managed to get two concurrent data processing tasks on the same user.  this can only happen if rabbitmq is either not atomic, or if rabbitmq does its whole totally-unnacceptable silent dropping of api calls thing.

Use of rabbitmq is now considered a bug, we are swapping to reddis as soon as I have dev time for it.

**Comment by biblicabeebli** [comment]
- https://github.com/onnela-lab/beiwe-backend/issues/93
- https://github.com/onnela-lab/beiwe-backend/issues/305
- https://github.com/onnela-lab/beiwe-backend/issues/353
- https://github.com/onnela-lab/beiwe-backend/issues/352
- https://github.com/onnela-lab/beiwe-backend/issues/331 - ubuntu platform upgrade - required before celery and rabbitmq.

**Comment by hackdna** [comment]
I recommend watching this talk before committing to replacement of RabbitMQ: https://2023.djangocon.us/talks/mixing-reliability-with-celery-for-delicious-async-tasks/

**Comment by biblicabeebli** [comment]
aaaaand celery 5.4 has redis bugs. https://github.com/celery/celery/milestone/40

**Comment by biblicabeebli** [comment]
deploy now uses updated ubuntu, python version, but something changed in rabbitmq configuration so I need to work that out.

**Comment by biblicabeebli** [comment]
keeping this open so that we update to 5.4 along with ubuntu 24.04....

**Comment by biblicabeebli** [comment]
Celery 5.4 is released, dogfooding on staging server (I've read release notes, no anticipated issues).

**Comment by biblicabeebli** [comment]
The original reason for which I opened this is actually more frequent after a Sentry update. Fantastic.

**Comment by biblicabeebli** [comment]
putting this issue on pause because I don't even know if redis will fix this.

**Comment by biblicabeebli** [comment]
closing issue, there is no need to change from rabbitmq at this time even with the problems it seems to cause as there's no evidence that these are not actually just celery problems.
